// @ts-nocheck
// AUTO-GENERATED by scripts/generate-mcp.ts — do not edit manually
import { z } from "zod";
import type { RegisterTools } from "../types";
import {
  READ_ONLY_ANNOTATIONS,
  WRITE_ANNOTATIONS,
  DESTRUCTIVE_ANNOTATIONS,
  toMcpResult,
  withErrorHandling,
} from "../types";
import {
  deleteDocument,
  deleteDocumentFavorite,
  deleteDocumentLabel,
  getDocument,
  getDocuments,
  getDocumentExtensions,
  getDocumentLabels,
  insertDocumentFavorite,
  insertDocumentLabel,
  moveDocumentToTrash,
  restoreDocument,
  upsertDocument,
  updateDocumentFavorite,
  updateDocumentLabels,
} from "~/modules/documents/documents.service";
import {
  documentValidator,
  documentLabelsValidator,
} from "~/modules/documents/documents.models";

export const registerDocumentsTools: RegisterTools = (server, ctx) => {
  server.registerTool(
    "documents_deleteDocument",
    {
      description: "delete document",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteDocument(ctx.client, params.id, ctx.userId);
      return toMcpResult(result);
    }, "Failed: documents_deleteDocument"),
  );

  server.registerTool(
    "documents_deleteDocumentFavorite",
    {
      description: "delete document favorite",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteDocumentFavorite(ctx.client, params.id, ctx.userId);
      return toMcpResult(result);
    }, "Failed: documents_deleteDocumentFavorite"),
  );

  server.registerTool(
    "documents_deleteDocumentLabel",
    {
      description: "delete document label",
      inputSchema: z.object({
      id: z.string(),
      label: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteDocumentLabel(ctx.client, params.id, params.label, ctx.userId);
      return toMcpResult(result);
    }, "Failed: documents_deleteDocumentLabel"),
  );

  server.registerTool(
    "documents_getDocument",
    {
      description: "get document",
      inputSchema: z.object({
      documentId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getDocument(ctx.client, params.documentId, ctx.userId);
      return toMcpResult(result);
    }, "Failed: documents_getDocument"),
  );

  server.registerTool(
    "documents_getDocuments",
    {
      description: "get documents",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable(),
    favorite: z.boolean().optional(),
    recent: z.boolean().optional(),
    active: z.boolean()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getDocuments(ctx.client, ctx.companyId, { ...params.args, createdBy: ctx.userId, companyId: ctx.companyId, userId: ctx.userId });
      return toMcpResult(result);
    }, "Failed: documents_getDocuments"),
  );

  server.registerTool(
    "documents_getDocumentExtensions",
    {
      description: "get document extensions",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getDocumentExtensions(ctx.client);
      return toMcpResult(result);
    }, "Failed: documents_getDocumentExtensions"),
  );

  server.registerTool(
    "documents_getDocumentLabels",
    {
      description: "get document labels",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getDocumentLabels(ctx.client, ctx.userId);
      return toMcpResult(result);
    }, "Failed: documents_getDocumentLabels"),
  );

  server.registerTool(
    "documents_insertDocumentFavorite",
    {
      description: "insert document favorite",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await insertDocumentFavorite(ctx.client, params.id, ctx.userId);
      return toMcpResult(result);
    }, "Failed: documents_insertDocumentFavorite"),
  );

  server.registerTool(
    "documents_insertDocumentLabel",
    {
      description: "insert document label",
      inputSchema: z.object({
      id: z.string(),
      label: z.string(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await insertDocumentLabel(ctx.client, params.id, params.label, ctx.userId);
      return toMcpResult(result);
    }, "Failed: documents_insertDocumentLabel"),
  );

  server.registerTool(
    "documents_moveDocumentToTrash",
    {
      description: "move document to trash",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await moveDocumentToTrash(ctx.client, params.id, ctx.userId);
      return toMcpResult(result);
    }, "Failed: documents_moveDocumentToTrash"),
  );

  server.registerTool(
    "documents_restoreDocument",
    {
      description: "restore document",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await restoreDocument(ctx.client, params.id, ctx.userId);
      return toMcpResult(result);
    }, "Failed: documents_restoreDocument"),
  );

  server.registerTool(
    "documents_upsertDocument",
    {
      description: "upsert document",
      inputSchema: z.object({
      document: documentValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertDocument(ctx.client, { ...params.document, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: documents_upsertDocument"),
  );

  server.registerTool(
    "documents_updateDocumentFavorite",
    {
      description: "update document favorite",
      inputSchema: z.object({
      args: z.object({
    id: z.string(),
    favorite: z.boolean()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateDocumentFavorite(ctx.client, { ...params.args, userId: ctx.userId });
      return toMcpResult(result);
    }, "Failed: documents_updateDocumentFavorite"),
  );

  server.registerTool(
    "documents_updateDocumentLabels",
    {
      description: "update document labels",
      inputSchema: z.object({
      document: documentLabelsValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateDocumentLabels(ctx.client, { ...params.document, userId: ctx.userId });
      return toMcpResult(result);
    }, "Failed: documents_updateDocumentLabels"),
  );
};
