// @ts-nocheck
// AUTO-GENERATED by scripts/generate-mcp.ts — do not edit manually
import { z } from "zod";
import type { RegisterTools } from "../types";
import {
  READ_ONLY_ANNOTATIONS,
  WRITE_ANNOTATIONS,
  DESTRUCTIVE_ANNOTATIONS,
  toMcpResult,
  withErrorHandling,
} from "../types";
import {
  activateMethodVersion,
  copyItem,
  copyMakeMethod,
  createRevision,
  deleteConfigurationParameter,
  deleteConfigurationRule,
  deleteItemCustomerPart,
  deleteConfigurationParameterGroup,
  deleteItem,
  deleteItemPostingGroup,
  deleteMaterialDimension,
  deleteMaterialFinish,
  deleteMaterialForm,
  deleteMaterialGrade,
  deleteMaterialSubstance,
  deleteMethodMaterial,
  assertMethodOperationIsDraft,
  deleteMethodOperationStep,
  deleteMethodOperationParameter,
  deleteMethodOperationTool,
  deleteUnitOfMeasure,
  getConfigurationParameters,
  getConfigurationRules,
  getConsumable,
  getConsumables,
  getConsumablesList,
  getItem,
  getItemCost,
  getItemCostHistory,
  getItemCustomerPart,
  getItemCustomerParts,
  getItemDemand,
  getItemFiles,
  getItemPostingGroup,
  getItemPostingGroups,
  getItemPostingGroupsList,
  getItemManufacturing,
  getItemPlanning,
  getItemQuantities,
  getItemReplenishment,
  getItemStorageUnitQuantities,
  getItemSupply,
  getItemUnitSalePrice,
  getMaterialUsedIn,
  getMakeMethods,
  getMakeMethodById,
  getMaterial,
  getMaterials,
  getMaterialsList,
  getMaterialDimension,
  getMaterialDimensions,
  getMaterialDimensionList,
  getMaterialFinish,
  getMaterialFinishes,
  getMaterialFinishList,
  getMaterialForm,
  getMaterialForms,
  getMaterialFormsList,
  getMaterialGrades,
  getMaterialGrade,
  getMaterialGradeList,
  getMaterialSubstance,
  getMaterialSubstances,
  getMaterialSubstancesList,
  getMethodMaterial,
  getMethodMaterials,
  getMethodMaterialsByMakeMethod,
  getMethodOperations,
  getMethodOperationsByMakeMethodId,
  getMethodTree,
  getMethodTreeArray,
  getOpenJobMaterials,
  getOpenProductionOrders,
  getOpenPurchaseOrderLines,
  getOpenSalesOrderLines,
  getPart,
  getParts,
  getPartsList,
  getPartUsedIn,
  getPickMethod,
  getPickMethods,
  getServices,
  getService,
  getServicesList,
  getSupplierParts,
  getTool,
  getTools,
  getToolsList,
  getUnitOfMeasure,
  getUnitOfMeasures,
  getUnitOfMeasuresList,
  updateConfigurationParameterGroupOrder,
  updateDefaultRevision,
  updateConfigurationParameterOrder,
  updateItemCost,
  updateMaterialOrder,
  updateOperationOrder,
  updateRevision,
  upsertConfigurationParameter,
  upsertConfigurationParameterGroup,
  upsertConfigurationRule,
  upsertConsumable,
  upsertPart,
  updateItem,
  upsertItemCost,
  upsertPickMethod,
  upsertItemManufacturing,
  upsertItemPlanning,
  upsertItemPurchasing,
  upsertItemPostingGroup,
  upsertSupplierPart,
  upsertItemCustomerPart,
  upsertItemUnitSalePrice,
  upsertMakeMethodVersion,
  upsertMethodMaterial,
  upsertMethodOperation,
  upsertMethodOperationStep,
  upsertMethodOperationParameter,
  upsertMethodOperationTool,
  upsertMaterial,
  upsertMaterialDimension,
  upsertMaterialFinish,
  upsertMaterialForm,
  upsertMaterialGrade,
  deleteMaterialType,
  getMaterialTypes,
  getMaterialType,
  getMaterialTypeList,
  upsertMaterialType,
  upsertMaterialSubstance,
  upsertService,
  upsertUnitOfMeasure,
  upsertTool,
  getSupplierPriceBreaksForItems,
  lookupBuyPrice,
  getSupplierPartPriceBreaks,
} from "~/modules/items/items.service";
import {
  getMethodValidator,
  configurationParameterGroupOrderValidator,
  configurationParameterOrderValidator,
  configurationParameterValidator,
  configurationRuleValidator,
  consumableValidator,
  partValidator,
  itemValidator,
  itemCostValidator,
  pickMethodValidator,
  itemManufacturingValidator,
  itemPlanningValidator,
  itemPurchasingValidator,
  itemPostingGroupValidator,
  supplierPartValidator,
  customerPartValidator,
  itemUnitSalePriceValidator,
  makeMethodVersionValidator,
  methodMaterialValidator,
  methodOperationValidator,
  materialValidator,
  materialDimensionValidator,
  materialFinishValidator,
  materialFormValidator,
  materialGradeValidator,
  materialTypeValidator,
  materialSubstanceValidator,
  serviceValidator,
  unitOfMeasureValidator,
  toolValidator,
} from "~/modules/items/items.models";
import {
  operationStepValidator,
  operationParameterValidator,
  operationToolValidator,
} from "~/modules/shared";

export const registerItemsTools: RegisterTools = (server, ctx) => {
  server.registerTool(
    "items_activateMethodVersion",
    {
      description: "activate method version",
      inputSchema: z.object({
      payload: z.object({
    id: z.string()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await activateMethodVersion(ctx.client, { ...params.payload, companyId: ctx.companyId, userId: ctx.userId });
      return toMcpResult(result);
    }, "Failed: items_activateMethodVersion"),
  );

  server.registerTool(
    "items_copyItem",
    {
      description: "copy item",
      inputSchema: z.object({
      args: getMethodValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await copyItem(ctx.client, { ...params.args, companyId: ctx.companyId, userId: ctx.userId });
      return toMcpResult(result);
    }, "Failed: items_copyItem"),
  );

  server.registerTool(
    "items_copyMakeMethod",
    {
      description: "copy make method",
      inputSchema: z.object({
      args: getMethodValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await copyMakeMethod(ctx.client, { ...params.args, companyId: ctx.companyId, userId: ctx.userId });
      return toMcpResult(result);
    }, "Failed: items_copyMakeMethod"),
  );

  server.registerTool(
    "items_createRevision",
    {
      description: "create revision",
      inputSchema: z.object({
      args: z.object({
    item: z.any(),
    revision: z.string()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await createRevision(ctx.client, { ...params.args, createdBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: items_createRevision"),
  );

  server.registerTool(
    "items_deleteConfigurationParameter",
    {
      description: "delete configuration parameter",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteConfigurationParameter(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: items_deleteConfigurationParameter"),
  );

  server.registerTool(
    "items_deleteConfigurationRule",
    {
      description: "delete configuration rule",
      inputSchema: z.object({
      field: z.string(),
      itemId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteConfigurationRule(ctx.client, params.field, params.itemId);
      return toMcpResult(result);
    }, "Failed: items_deleteConfigurationRule"),
  );

  server.registerTool(
    "items_deleteItemCustomerPart",
    {
      description: "delete item customer part",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteItemCustomerPart(ctx.client, params.id, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: items_deleteItemCustomerPart"),
  );

  server.registerTool(
    "items_deleteConfigurationParameterGroup",
    {
      description: "delete configuration parameter group",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteConfigurationParameterGroup(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: items_deleteConfigurationParameterGroup"),
  );

  server.registerTool(
    "items_deleteItem",
    {
      description: "delete item",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteItem(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: items_deleteItem"),
  );

  server.registerTool(
    "items_deleteItemPostingGroup",
    {
      description: "delete item posting group",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteItemPostingGroup(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: items_deleteItemPostingGroup"),
  );

  server.registerTool(
    "items_deleteMaterialDimension",
    {
      description: "delete material dimension",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteMaterialDimension(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: items_deleteMaterialDimension"),
  );

  server.registerTool(
    "items_deleteMaterialFinish",
    {
      description: "delete material finish",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteMaterialFinish(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: items_deleteMaterialFinish"),
  );

  server.registerTool(
    "items_deleteMaterialForm",
    {
      description: "delete material form",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteMaterialForm(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: items_deleteMaterialForm"),
  );

  server.registerTool(
    "items_deleteMaterialGrade",
    {
      description: "delete material grade",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteMaterialGrade(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: items_deleteMaterialGrade"),
  );

  server.registerTool(
    "items_deleteMaterialSubstance",
    {
      description: "delete material substance",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteMaterialSubstance(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: items_deleteMaterialSubstance"),
  );

  server.registerTool(
    "items_deleteMethodMaterial",
    {
      description: "delete method material",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteMethodMaterial(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: items_deleteMethodMaterial"),
  );

  server.registerTool(
    "items_assertMethodOperationIsDraft",
    {
      description: "assert method operation is draft",
      inputSchema: z.object({
      operationId: z.string(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await assertMethodOperationIsDraft(ctx.client, params.operationId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: items_assertMethodOperationIsDraft"),
  );

  server.registerTool(
    "items_deleteMethodOperationStep",
    {
      description: "delete method operation step",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteMethodOperationStep(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: items_deleteMethodOperationStep"),
  );

  server.registerTool(
    "items_deleteMethodOperationParameter",
    {
      description: "delete method operation parameter",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteMethodOperationParameter(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: items_deleteMethodOperationParameter"),
  );

  server.registerTool(
    "items_deleteMethodOperationTool",
    {
      description: "delete method operation tool",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteMethodOperationTool(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: items_deleteMethodOperationTool"),
  );

  server.registerTool(
    "items_deleteUnitOfMeasure",
    {
      description: "delete unit of measure",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteUnitOfMeasure(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: items_deleteUnitOfMeasure"),
  );

  server.registerTool(
    "items_getConfigurationParameters",
    {
      description: "get configuration parameters",
      inputSchema: z.object({
      itemId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getConfigurationParameters(ctx.client, params.itemId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: items_getConfigurationParameters"),
  );

  server.registerTool(
    "items_getConfigurationRules",
    {
      description: "get configuration rules",
      inputSchema: z.object({
      itemId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getConfigurationRules(ctx.client, params.itemId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: items_getConfigurationRules"),
  );

  server.registerTool(
    "items_getConsumable",
    {
      description: "get consumable",
      inputSchema: z.object({
      itemId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getConsumable(ctx.client, params.itemId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: items_getConsumable"),
  );

  server.registerTool(
    "items_getConsumables",
    {
      description: "get consumables",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable(),
    supplierId: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getConsumables(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: items_getConsumables"),
  );

  server.registerTool(
    "items_getConsumablesList",
    {
      description: "get consumables list",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getConsumablesList(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: items_getConsumablesList"),
  );

  server.registerTool(
    "items_getItem",
    {
      description: "get item",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getItem(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: items_getItem"),
  );

  server.registerTool(
    "items_getItemCost",
    {
      description: "get item cost",
      inputSchema: z.object({
      itemId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getItemCost(ctx.client, params.itemId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: items_getItemCost"),
  );

  server.registerTool(
    "items_getItemCostHistory",
    {
      description: "get item cost history",
      inputSchema: z.object({
      itemId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getItemCostHistory(ctx.client, params.itemId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: items_getItemCostHistory"),
  );

  server.registerTool(
    "items_getItemCustomerPart",
    {
      description: "get item customer part",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getItemCustomerPart(ctx.client, params.id, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: items_getItemCustomerPart"),
  );

  server.registerTool(
    "items_getItemCustomerParts",
    {
      description: "get item customer parts",
      inputSchema: z.object({
      itemId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getItemCustomerParts(ctx.client, params.itemId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: items_getItemCustomerParts"),
  );

  server.registerTool(
    "items_getItemDemand",
    {
      description: "get item demand",
      inputSchema: z.object({
      arg1: z.object({
    itemId: z.string(),
    locationId: z.string(),
    periods: z.array(z.string())
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getItemDemand(ctx.client, { ...params.arg1, companyId: ctx.companyId });
      return toMcpResult(result);
    }, "Failed: items_getItemDemand"),
  );

  server.registerTool(
    "items_getItemFiles",
    {
      description: "get item files",
      inputSchema: z.object({
      itemId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getItemFiles(ctx.client, params.itemId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: items_getItemFiles"),
  );

  server.registerTool(
    "items_getItemPostingGroup",
    {
      description: "get item posting group",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getItemPostingGroup(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: items_getItemPostingGroup"),
  );

  server.registerTool(
    "items_getItemPostingGroups",
    {
      description: "get item posting groups",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getItemPostingGroups(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: items_getItemPostingGroups"),
  );

  server.registerTool(
    "items_getItemPostingGroupsList",
    {
      description: "get item posting groups list",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getItemPostingGroupsList(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: items_getItemPostingGroupsList"),
  );

  server.registerTool(
    "items_getItemManufacturing",
    {
      description: "get item manufacturing",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getItemManufacturing(ctx.client, params.id, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: items_getItemManufacturing"),
  );

  server.registerTool(
    "items_getItemPlanning",
    {
      description: "get item planning",
      inputSchema: z.object({
      itemId: z.string(),
      locationId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getItemPlanning(ctx.client, params.itemId, ctx.companyId, params.locationId);
      return toMcpResult(result);
    }, "Failed: items_getItemPlanning"),
  );

  server.registerTool(
    "items_getItemQuantities",
    {
      description: "get item quantities",
      inputSchema: z.object({
      itemId: z.string(),
      locationId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getItemQuantities(ctx.client, params.itemId, ctx.companyId, params.locationId);
      return toMcpResult(result);
    }, "Failed: items_getItemQuantities"),
  );

  server.registerTool(
    "items_getItemReplenishment",
    {
      description: "get item replenishment",
      inputSchema: z.object({
      itemId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getItemReplenishment(ctx.client, params.itemId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: items_getItemReplenishment"),
  );

  server.registerTool(
    "items_getItemStorageUnitQuantities",
    {
      description: "get item storage unit quantities",
      inputSchema: z.object({
      itemId: z.string(),
      locationId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getItemStorageUnitQuantities(ctx.client, params.itemId, ctx.companyId, params.locationId);
      return toMcpResult(result);
    }, "Failed: items_getItemStorageUnitQuantities"),
  );

  server.registerTool(
    "items_getItemSupply",
    {
      description: "get item supply",
      inputSchema: z.object({
      arg1: z.object({
    itemId: z.string(),
    locationId: z.string(),
    periods: z.array(z.string())
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getItemSupply(ctx.client, { ...params.arg1, companyId: ctx.companyId });
      return toMcpResult(result);
    }, "Failed: items_getItemSupply"),
  );

  server.registerTool(
    "items_getItemUnitSalePrice",
    {
      description: "get item unit sale price",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getItemUnitSalePrice(ctx.client, params.id, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: items_getItemUnitSalePrice"),
  );

  server.registerTool(
    "items_getMaterialUsedIn",
    {
      description: "get material used in",
      inputSchema: z.object({
      itemId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMaterialUsedIn(ctx.client, params.itemId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: items_getMaterialUsedIn"),
  );

  server.registerTool(
    "items_getMakeMethods",
    {
      description: "get make methods",
      inputSchema: z.object({
      itemId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMakeMethods(ctx.client, params.itemId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: items_getMakeMethods"),
  );

  server.registerTool(
    "items_getMakeMethodById",
    {
      description: "get make method by id",
      inputSchema: z.object({
      makeMethodId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMakeMethodById(ctx.client, params.makeMethodId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: items_getMakeMethodById"),
  );

  server.registerTool(
    "items_getMaterial",
    {
      description: "get material",
      inputSchema: z.object({
      itemId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMaterial(ctx.client, params.itemId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: items_getMaterial"),
  );

  server.registerTool(
    "items_getMaterials",
    {
      description: "get materials",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable(),
    supplierId: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMaterials(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: items_getMaterials"),
  );

  server.registerTool(
    "items_getMaterialsList",
    {
      description: "get materials list",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMaterialsList(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: items_getMaterialsList"),
  );

  server.registerTool(
    "items_getMaterialDimension",
    {
      description: "get material dimension",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMaterialDimension(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: items_getMaterialDimension"),
  );

  server.registerTool(
    "items_getMaterialDimensions",
    {
      description: "get material dimensions",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable(),
    isMetric: z.boolean()
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMaterialDimensions(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: items_getMaterialDimensions"),
  );

  server.registerTool(
    "items_getMaterialDimensionList",
    {
      description: "get material dimension list",
      inputSchema: z.object({
      materialFormId: z.string(),
      isMetric: z.boolean(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMaterialDimensionList(ctx.client, params.materialFormId, params.isMetric, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: items_getMaterialDimensionList"),
  );

  server.registerTool(
    "items_getMaterialFinish",
    {
      description: "get material finish",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMaterialFinish(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: items_getMaterialFinish"),
  );

  server.registerTool(
    "items_getMaterialFinishes",
    {
      description: "get material finishes",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMaterialFinishes(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: items_getMaterialFinishes"),
  );

  server.registerTool(
    "items_getMaterialFinishList",
    {
      description: "get material finish list",
      inputSchema: z.object({
      materialSubstanceId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMaterialFinishList(ctx.client, params.materialSubstanceId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: items_getMaterialFinishList"),
  );

  server.registerTool(
    "items_getMaterialForm",
    {
      description: "get material form",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMaterialForm(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: items_getMaterialForm"),
  );

  server.registerTool(
    "items_getMaterialForms",
    {
      description: "get material forms",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMaterialForms(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: items_getMaterialForms"),
  );

  server.registerTool(
    "items_getMaterialFormsList",
    {
      description: "get material forms list",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMaterialFormsList(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: items_getMaterialFormsList"),
  );

  server.registerTool(
    "items_getMaterialGrades",
    {
      description: "get material grades",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMaterialGrades(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: items_getMaterialGrades"),
  );

  server.registerTool(
    "items_getMaterialGrade",
    {
      description: "get material grade",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMaterialGrade(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: items_getMaterialGrade"),
  );

  server.registerTool(
    "items_getMaterialGradeList",
    {
      description: "get material grade list",
      inputSchema: z.object({
      materialSubstanceId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMaterialGradeList(ctx.client, params.materialSubstanceId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: items_getMaterialGradeList"),
  );

  server.registerTool(
    "items_getMaterialSubstance",
    {
      description: "get material substance",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMaterialSubstance(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: items_getMaterialSubstance"),
  );

  server.registerTool(
    "items_getMaterialSubstances",
    {
      description: "get material substances",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMaterialSubstances(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: items_getMaterialSubstances"),
  );

  server.registerTool(
    "items_getMaterialSubstancesList",
    {
      description: "get material substances list",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMaterialSubstancesList(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: items_getMaterialSubstancesList"),
  );

  server.registerTool(
    "items_getMethodMaterial",
    {
      description: "get method material",
      inputSchema: z.object({
      materialId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMethodMaterial(ctx.client, params.materialId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: items_getMethodMaterial"),
  );

  server.registerTool(
    "items_getMethodMaterials",
    {
      description: "get method materials",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMethodMaterials(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: items_getMethodMaterials"),
  );

  server.registerTool(
    "items_getMethodMaterialsByMakeMethod",
    {
      description: "get method materials by make method",
      inputSchema: z.object({
      makeMethodId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMethodMaterialsByMakeMethod(ctx.client, params.makeMethodId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: items_getMethodMaterialsByMakeMethod"),
  );

  server.registerTool(
    "items_getMethodOperations",
    {
      description: "get method operations",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMethodOperations(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: items_getMethodOperations"),
  );

  server.registerTool(
    "items_getMethodOperationsByMakeMethodId",
    {
      description: "get method operations by make method id",
      inputSchema: z.object({
      makeMethodId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMethodOperationsByMakeMethodId(ctx.client, params.makeMethodId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: items_getMethodOperationsByMakeMethodId"),
  );

  server.registerTool(
    "items_getMethodTree",
    {
      description: "get method tree",
      inputSchema: z.object({
      makeMethodId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMethodTree(
        ctx.client,
        params.makeMethodId,
        ctx.companyId
      );
      return toMcpResult(result);
    }, "Failed: items_getMethodTree"),
  );

  server.registerTool(
    "items_getMethodTreeArray",
    {
      description: "get method tree array",
      inputSchema: z.object({
      makeMethodId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMethodTreeArray(
        ctx.client,
        params.makeMethodId,
        ctx.companyId
      );
      return toMcpResult(result);
    }, "Failed: items_getMethodTreeArray"),
  );

  server.registerTool(
    "items_getOpenJobMaterials",
    {
      description: "get open job materials",
      inputSchema: z.object({
      arg1: z.object({
    itemId: z.string(),
    locationId: z.string()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getOpenJobMaterials(ctx.client, { ...params.arg1, companyId: ctx.companyId });
      return toMcpResult(result);
    }, "Failed: items_getOpenJobMaterials"),
  );

  server.registerTool(
    "items_getOpenProductionOrders",
    {
      description: "get open production orders",
      inputSchema: z.object({
      arg1: z.object({
    itemId: z.string(),
    locationId: z.string()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getOpenProductionOrders(ctx.client, { ...params.arg1, companyId: ctx.companyId });
      return toMcpResult(result);
    }, "Failed: items_getOpenProductionOrders"),
  );

  server.registerTool(
    "items_getOpenPurchaseOrderLines",
    {
      description: "get open purchase order lines",
      inputSchema: z.object({
      arg1: z.object({
    itemId: z.string(),
    locationId: z.string()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getOpenPurchaseOrderLines(ctx.client, { ...params.arg1, companyId: ctx.companyId });
      return toMcpResult(result);
    }, "Failed: items_getOpenPurchaseOrderLines"),
  );

  server.registerTool(
    "items_getOpenSalesOrderLines",
    {
      description: "get open sales order lines",
      inputSchema: z.object({
      arg1: z.object({
    itemId: z.string(),
    locationId: z.string()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getOpenSalesOrderLines(ctx.client, { ...params.arg1, companyId: ctx.companyId });
      return toMcpResult(result);
    }, "Failed: items_getOpenSalesOrderLines"),
  );

  server.registerTool(
    "items_getPart",
    {
      description: "get part",
      inputSchema: z.object({
      itemId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPart(ctx.client, params.itemId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: items_getPart"),
  );

  server.registerTool(
    "items_getParts",
    {
      description: "get parts",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable(),
    supplierId: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getParts(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: items_getParts"),
  );

  server.registerTool(
    "items_getPartsList",
    {
      description: "get parts list",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPartsList(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: items_getPartsList"),
  );

  server.registerTool(
    "items_getPartUsedIn",
    {
      description: "get part used in",
      inputSchema: z.object({
      itemId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPartUsedIn(ctx.client, params.itemId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: items_getPartUsedIn"),
  );

  server.registerTool(
    "items_getPickMethod",
    {
      description: "get pick method",
      inputSchema: z.object({
      itemId: z.string(),
      locationId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPickMethod(ctx.client, params.itemId, ctx.companyId, params.locationId);
      return toMcpResult(result);
    }, "Failed: items_getPickMethod"),
  );

  server.registerTool(
    "items_getPickMethods",
    {
      description: "get pick methods",
      inputSchema: z.object({
      itemId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPickMethods(ctx.client, params.itemId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: items_getPickMethods"),
  );

  server.registerTool(
    "items_getServices",
    {
      description: "get services",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable(),
    type: z.string().nullable(),
    group: z.string().nullable(),
    supplierId: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getServices(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: items_getServices"),
  );

  server.registerTool(
    "items_getService",
    {
      description: "get service",
      inputSchema: z.object({
      itemId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getService(ctx.client, params.itemId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: items_getService"),
  );

  server.registerTool(
    "items_getServicesList",
    {
      description: "get services list",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getServicesList(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: items_getServicesList"),
  );

  server.registerTool(
    "items_getSupplierParts",
    {
      description: "get supplier parts",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSupplierParts(ctx.client, params.id, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: items_getSupplierParts"),
  );

  server.registerTool(
    "items_getTool",
    {
      description: "get tool",
      inputSchema: z.object({
      itemId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getTool(ctx.client, params.itemId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: items_getTool"),
  );

  server.registerTool(
    "items_getTools",
    {
      description: "get tools",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable(),
    supplierId: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getTools(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: items_getTools"),
  );

  server.registerTool(
    "items_getToolsList",
    {
      description: "get tools list",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getToolsList(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: items_getToolsList"),
  );

  server.registerTool(
    "items_getUnitOfMeasure",
    {
      description: "get unit of measure",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getUnitOfMeasure(ctx.client, params.id, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: items_getUnitOfMeasure"),
  );

  server.registerTool(
    "items_getUnitOfMeasures",
    {
      description: "get unit of measures",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getUnitOfMeasures(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: items_getUnitOfMeasures"),
  );

  server.registerTool(
    "items_getUnitOfMeasuresList",
    {
      description: "get unit of measures list",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getUnitOfMeasuresList(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: items_getUnitOfMeasuresList"),
  );

  server.registerTool(
    "items_updateConfigurationParameterGroupOrder",
    {
      description: "update configuration parameter group order",
      inputSchema: z.object({
      data: configurationParameterGroupOrderValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateConfigurationParameterGroupOrder(ctx.client, params.data);
      return toMcpResult(result);
    }, "Failed: items_updateConfigurationParameterGroupOrder"),
  );

  server.registerTool(
    "items_updateDefaultRevision",
    {
      description: "update default revision",
      inputSchema: z.object({
      data: z.object({
    id: z.string()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateDefaultRevision(ctx.client, { ...params.data, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: items_updateDefaultRevision"),
  );

  server.registerTool(
    "items_updateConfigurationParameterOrder",
    {
      description: "update configuration parameter order",
      inputSchema: z.object({
      data: configurationParameterOrderValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateConfigurationParameterOrder(ctx.client, { ...params.data, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: items_updateConfigurationParameterOrder"),
  );

  server.registerTool(
    "items_updateItemCost",
    {
      description: "update item cost",
      inputSchema: z.object({
      itemId: z.string(),
      cost: z.object({
    unitCost: z.number()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateItemCost(ctx.client, params.itemId, { ...params.cost, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: items_updateItemCost"),
  );

  server.registerTool(
    "items_updateMaterialOrder",
    {
      description: "update material order",
      inputSchema: z.object({
      updates: z.object({
    id: z.string(),
    order: z.number()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateMaterialOrder(ctx.client, { ...params.updates, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: items_updateMaterialOrder"),
  );

  server.registerTool(
    "items_updateOperationOrder",
    {
      description: "update operation order",
      inputSchema: z.object({
      updates: z.object({
    id: z.string(),
    order: z.number()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateOperationOrder(ctx.client, { ...params.updates, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: items_updateOperationOrder"),
  );

  server.registerTool(
    "items_updateRevision",
    {
      description: "update revision",
      inputSchema: z.object({
      revision: z.object({
    id: z.string(),
    revision: z.string()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateRevision(ctx.client, { ...params.revision, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: items_updateRevision"),
  );

  server.registerTool(
    "items_upsertConfigurationParameter",
    {
      description: "upsert configuration parameter",
      inputSchema: z.object({
      configurationParameter: configurationParameterValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertConfigurationParameter(ctx.client, { ...params.configurationParameter, companyId: ctx.companyId, userId: ctx.userId });
      return toMcpResult(result);
    }, "Failed: items_upsertConfigurationParameter"),
  );

  server.registerTool(
    "items_upsertConfigurationParameterGroup",
    {
      description: "upsert configuration parameter group",
      inputSchema: z.object({
      configurationParameterGroup: z.any(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertConfigurationParameterGroup(ctx.client, { ...params.configurationParameterGroup, companyId: ctx.companyId });
      return toMcpResult(result);
    }, "Failed: items_upsertConfigurationParameterGroup"),
  );

  server.registerTool(
    "items_upsertConfigurationRule",
    {
      description: "upsert configuration rule",
      inputSchema: z.object({
      configurationRule: configurationRuleValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertConfigurationRule(ctx.client, { ...params.configurationRule, companyId: ctx.companyId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: items_upsertConfigurationRule"),
  );

  server.registerTool(
    "items_upsertConsumable",
    {
      description: "upsert consumable",
      inputSchema: z.object({
      consumable: consumableValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertConsumable(ctx.client, { ...params.consumable, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: items_upsertConsumable"),
  );

  server.registerTool(
    "items_upsertPart",
    {
      description: "upsert part",
      inputSchema: z.object({
      part: partValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertPart(ctx.client, { ...params.part, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: items_upsertPart"),
  );

  server.registerTool(
    "items_updateItem",
    {
      description: "update item",
      inputSchema: z.object({
      item: itemValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateItem(ctx.client, { ...params.item, companyId: ctx.companyId });
      return toMcpResult(result);
    }, "Failed: items_updateItem"),
  );

  server.registerTool(
    "items_upsertItemCost",
    {
      description: "upsert item cost",
      inputSchema: z.object({
      itemCost: itemCostValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertItemCost(ctx.client, { ...params.itemCost, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: items_upsertItemCost"),
  );

  server.registerTool(
    "items_upsertPickMethod",
    {
      description: "upsert pick method",
      inputSchema: z.object({
      pickMethod: pickMethodValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertPickMethod(ctx.client, { ...params.pickMethod, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: items_upsertPickMethod"),
  );

  server.registerTool(
    "items_upsertItemManufacturing",
    {
      description: "upsert item manufacturing",
      inputSchema: z.object({
      partManufacturing: itemManufacturingValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertItemManufacturing(ctx.client, { ...params.partManufacturing, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: items_upsertItemManufacturing"),
  );

  server.registerTool(
    "items_upsertItemPlanning",
    {
      description: "upsert item planning",
      inputSchema: z.object({
      partPlanning: itemPlanningValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertItemPlanning(ctx.client, { ...params.partPlanning, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: items_upsertItemPlanning"),
  );

  server.registerTool(
    "items_upsertItemPurchasing",
    {
      description: "upsert item purchasing",
      inputSchema: z.object({
      itemPurchasing: itemPurchasingValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertItemPurchasing(ctx.client, { ...params.itemPurchasing, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: items_upsertItemPurchasing"),
  );

  server.registerTool(
    "items_upsertItemPostingGroup",
    {
      description: "upsert item posting group",
      inputSchema: z.object({
      itemPostingGroup: itemPostingGroupValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertItemPostingGroup(ctx.client, { ...params.itemPostingGroup, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: items_upsertItemPostingGroup"),
  );

  server.registerTool(
    "items_upsertSupplierPart",
    {
      description: "upsert supplier part",
      inputSchema: z.object({
      supplierPart: supplierPartValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertSupplierPart(ctx.client, { ...params.supplierPart, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: items_upsertSupplierPart"),
  );

  server.registerTool(
    "items_upsertItemCustomerPart",
    {
      description: "upsert item customer part",
      inputSchema: z.object({
      customerPart: customerPartValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertItemCustomerPart(ctx.client, { ...params.customerPart, companyId: ctx.companyId });
      return toMcpResult(result);
    }, "Failed: items_upsertItemCustomerPart"),
  );

  server.registerTool(
    "items_upsertItemUnitSalePrice",
    {
      description: "upsert item unit sale price",
      inputSchema: z.object({
      itemUnitSalePrice: itemUnitSalePriceValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertItemUnitSalePrice(ctx.client, { ...params.itemUnitSalePrice, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: items_upsertItemUnitSalePrice"),
  );

  server.registerTool(
    "items_upsertMakeMethodVersion",
    {
      description: "upsert make method version",
      inputSchema: z.object({
      makeMethodVersion: makeMethodVersionValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertMakeMethodVersion(ctx.client, { ...params.makeMethodVersion, companyId: ctx.companyId, createdBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: items_upsertMakeMethodVersion"),
  );

  server.registerTool(
    "items_upsertMethodMaterial",
    {
      description: "upsert method material",
      inputSchema: z.object({
      methodMaterial: methodMaterialValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertMethodMaterial(ctx.client, { ...params.methodMaterial, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: items_upsertMethodMaterial"),
  );

  server.registerTool(
    "items_upsertMethodOperation",
    {
      description: "upsert method operation",
      inputSchema: z.object({
      methodOperation: methodOperationValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertMethodOperation(ctx.client, { ...params.methodOperation, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: items_upsertMethodOperation"),
  );

  server.registerTool(
    "items_upsertMethodOperationStep",
    {
      description: "upsert method operation step",
      inputSchema: z.object({
      methodOperationStep: operationStepValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertMethodOperationStep(ctx.client, { ...params.methodOperationStep, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: items_upsertMethodOperationStep"),
  );

  server.registerTool(
    "items_upsertMethodOperationParameter",
    {
      description: "upsert method operation parameter",
      inputSchema: z.object({
      methodOperationParameter: operationParameterValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertMethodOperationParameter(ctx.client, { ...params.methodOperationParameter, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: items_upsertMethodOperationParameter"),
  );

  server.registerTool(
    "items_upsertMethodOperationTool",
    {
      description: "upsert method operation tool",
      inputSchema: z.object({
      methodOperationTool: operationToolValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertMethodOperationTool(ctx.client, { ...params.methodOperationTool, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: items_upsertMethodOperationTool"),
  );

  server.registerTool(
    "items_upsertMaterial",
    {
      description: "upsert material",
      inputSchema: z.object({
      material: materialValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertMaterial(ctx.client, { ...params.material, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: items_upsertMaterial"),
  );

  server.registerTool(
    "items_upsertMaterialDimension",
    {
      description: "upsert material dimension",
      inputSchema: z.object({
      materialDimension: materialDimensionValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertMaterialDimension(ctx.client, { ...params.materialDimension, companyId: ctx.companyId });
      return toMcpResult(result);
    }, "Failed: items_upsertMaterialDimension"),
  );

  server.registerTool(
    "items_upsertMaterialFinish",
    {
      description: "upsert material finish",
      inputSchema: z.object({
      materialFinish: materialFinishValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertMaterialFinish(ctx.client, { ...params.materialFinish, companyId: ctx.companyId });
      return toMcpResult(result);
    }, "Failed: items_upsertMaterialFinish"),
  );

  server.registerTool(
    "items_upsertMaterialForm",
    {
      description: "upsert material form",
      inputSchema: z.object({
      materialForm: materialFormValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertMaterialForm(ctx.client, { ...params.materialForm, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: items_upsertMaterialForm"),
  );

  server.registerTool(
    "items_upsertMaterialGrade",
    {
      description: "upsert material grade",
      inputSchema: z.object({
      materialGrade: materialGradeValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertMaterialGrade(ctx.client, { ...params.materialGrade, companyId: ctx.companyId });
      return toMcpResult(result);
    }, "Failed: items_upsertMaterialGrade"),
  );

  server.registerTool(
    "items_deleteMaterialType",
    {
      description: "delete material type",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteMaterialType(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: items_deleteMaterialType"),
  );

  server.registerTool(
    "items_getMaterialTypes",
    {
      description: "get material types",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMaterialTypes(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: items_getMaterialTypes"),
  );

  server.registerTool(
    "items_getMaterialType",
    {
      description: "get material type",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMaterialType(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: items_getMaterialType"),
  );

  server.registerTool(
    "items_getMaterialTypeList",
    {
      description: "get material type list",
      inputSchema: z.object({
      materialSubstanceId: z.string(),
      materialFormId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMaterialTypeList(ctx.client, params.materialSubstanceId, params.materialFormId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: items_getMaterialTypeList"),
  );

  server.registerTool(
    "items_upsertMaterialType",
    {
      description: "upsert material type",
      inputSchema: z.object({
      materialType: materialTypeValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertMaterialType(ctx.client, { ...params.materialType, companyId: ctx.companyId });
      return toMcpResult(result);
    }, "Failed: items_upsertMaterialType"),
  );

  server.registerTool(
    "items_upsertMaterialSubstance",
    {
      description: "upsert material substance",
      inputSchema: z.object({
      materialSubstance: materialSubstanceValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertMaterialSubstance(ctx.client, { ...params.materialSubstance, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: items_upsertMaterialSubstance"),
  );

  server.registerTool(
    "items_upsertService",
    {
      description: "upsert service",
      inputSchema: z.object({
      service: serviceValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertService(ctx.client, { ...params.service, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: items_upsertService"),
  );

  server.registerTool(
    "items_upsertUnitOfMeasure",
    {
      description: "upsert unit of measure",
      inputSchema: z.object({
      unitOfMeasure: unitOfMeasureValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertUnitOfMeasure(ctx.client, { ...params.unitOfMeasure, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: items_upsertUnitOfMeasure"),
  );

  server.registerTool(
    "items_upsertTool",
    {
      description: "upsert tool",
      inputSchema: z.object({
      tool: toolValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertTool(ctx.client, { ...params.tool, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: items_upsertTool"),
  );

  server.registerTool(
    "items_getSupplierPriceBreaksForItems",
    {
      description: "get supplier price breaks for items",
      inputSchema: z.object({
      itemIds: z.array(z.string()),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSupplierPriceBreaksForItems(ctx.client, params.itemIds);
      return toMcpResult(result);
    }, "Failed: items_getSupplierPriceBreaksForItems"),
  );

  server.registerTool(
    "items_lookupBuyPrice",
    {
      description: "lookup buy price",
      inputSchema: z.object({
      itemId: z.string(),
      qty: z.number(),
      fallbackCost: z.number(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await lookupBuyPrice(ctx.client, params.itemId, params.qty, params.fallbackCost);
      return toMcpResult(result);
    }, "Failed: items_lookupBuyPrice"),
  );

  server.registerTool(
    "items_getSupplierPartPriceBreaks",
    {
      description: "get supplier part price breaks",
      inputSchema: z.object({
      supplierPartId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSupplierPartPriceBreaks(ctx.client, params.supplierPartId);
      return toMcpResult(result);
    }, "Failed: items_getSupplierPartPriceBreaks"),
  );
};
