// @ts-nocheck
// AUTO-GENERATED by scripts/generate-mcp.ts — do not edit manually
import { z } from "zod";
import type { RegisterTools } from "../types";
import {
  READ_ONLY_ANNOTATIONS,
  WRITE_ANNOTATIONS,
  DESTRUCTIVE_ANNOTATIONS,
  toMcpResult,
  withErrorHandling,
} from "../types";
import {
  canApproveRequest,
  canApproveRequestInWindow,
  cancelApprovalRequest,
  canViewApprovalRequest,
  createApprovalRequest,
  deleteApprovalRule,
  deleteNote,
  deleteSavedView,
  generateEmbedding,
  getApprovalById,
  getApprovalRequestsByDocument,
  getApprovalRuleByAmount,
  getApproverUserIdsForRule,
  getApprovalRuleById,
  getApprovalRules,
  getApprovalRulesForApprover,
  getApprovalsForUser,
  getBase64ImageFromStorage,
  getCountries,
  getLatestApprovalRequestForDocument,
  getModelByItemId,
  getNotes,
  getPendingApprovalsForApprover,
  getPeriods,
  getSavedViews,
  getTagsList,
  hasPendingApproval,
  importCsv,
  insertNote,
  insertTag,
  isApprovalRequired,
  getExternalLink,
  upsertExternalLink,
  getCustomerPortals,
  getCustomerPortal,
  deleteCustomerPortal,
  updateModelThumbnail,
  upsertModelUpload,
  updateNote,
  upsertApprovalRule,
  upsertSavedView,
  updateSavedViewOrder,
} from "~/modules/shared/shared.service";
import {
  approveRequest,
  rejectRequest,
} from "~/modules/shared/shared.server";

export const registerSharedTools: RegisterTools = (server, ctx) => {
  server.registerTool(
    "shared_approveRequest",
    {
      description: "approve request",
      inputSchema: z.object({
      id: z.string(),
      notes: z.string().optional(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await approveRequest(params.id, ctx.userId, params.notes);
      return toMcpResult(result);
    }, "Failed: shared_approveRequest"),
  );

  server.registerTool(
    "shared_canApproveRequest",
    {
      description: "can approve request",
      inputSchema: z.object({
      approvalRequest: z.any(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await canApproveRequest(ctx.client, params.approvalRequest, ctx.userId);
      return toMcpResult(result);
    }, "Failed: shared_canApproveRequest"),
  );

  server.registerTool(
    "shared_canApproveRequestInWindow",
    {
      description: "can approve request in window",
      inputSchema: z.object({
      approvalRequest: z.any(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await canApproveRequestInWindow(ctx.client, params.approvalRequest, ctx.userId);
      return toMcpResult(result);
    }, "Failed: shared_canApproveRequestInWindow"),
  );

  server.registerTool(
    "shared_cancelApprovalRequest",
    {
      description: "cancel approval request",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await cancelApprovalRequest(ctx.client, params.id, ctx.userId);
      return toMcpResult(result);
    }, "Failed: shared_cancelApprovalRequest"),
  );

  server.registerTool(
    "shared_canViewApprovalRequest",
    {
      description: "can view approval request",
      inputSchema: z.object({
      approvalRequest: z.any(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await canViewApprovalRequest(ctx.client, params.approvalRequest, ctx.userId);
      return toMcpResult(result);
    }, "Failed: shared_canViewApprovalRequest"),
  );

  server.registerTool(
    "shared_createApprovalRequest",
    {
      description: "create approval request",
      inputSchema: z.object({
      request: z.any(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await createApprovalRequest(ctx.client, params.request);
      return toMcpResult(result);
    }, "Failed: shared_createApprovalRequest"),
  );

  server.registerTool(
    "shared_deleteApprovalRule",
    {
      description: "delete approval rule",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteApprovalRule(ctx.client, params.id, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: shared_deleteApprovalRule"),
  );

  server.registerTool(
    "shared_deleteNote",
    {
      description: "delete note",
      inputSchema: z.object({
      noteId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteNote(ctx.client, params.noteId);
      return toMcpResult(result);
    }, "Failed: shared_deleteNote"),
  );

  server.registerTool(
    "shared_deleteSavedView",
    {
      description: "delete saved view",
      inputSchema: z.object({
      viewId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteSavedView(ctx.client, params.viewId);
      return toMcpResult(result);
    }, "Failed: shared_deleteSavedView"),
  );

  server.registerTool(
    "shared_generateEmbedding",
    {
      description: "generate embedding",
      inputSchema: z.object({
      text: z.string(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await generateEmbedding(ctx.client, params.text);
      return toMcpResult(result);
    }, "Failed: shared_generateEmbedding"),
  );

  server.registerTool(
    "shared_getApprovalById",
    {
      description: "get approval by id",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getApprovalById(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: shared_getApprovalById"),
  );

  server.registerTool(
    "shared_getApprovalRequestsByDocument",
    {
      description: "get approval requests by document",
      inputSchema: z.object({
      documentType: z.any(),
      documentId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getApprovalRequestsByDocument(ctx.client, params.documentType, params.documentId);
      return toMcpResult(result);
    }, "Failed: shared_getApprovalRequestsByDocument"),
  );

  server.registerTool(
    "shared_getApprovalRuleByAmount",
    {
      description: "get approval rule by amount",
      inputSchema: z.object({
      documentType: z.any(),
      amount: z.number().optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getApprovalRuleByAmount(ctx.client, params.documentType, ctx.companyId, params.amount);
      return toMcpResult(result);
    }, "Failed: shared_getApprovalRuleByAmount"),
  );

  server.registerTool(
    "shared_getApproverUserIdsForRule",
    {
      description: "get approver user ids for rule",
      inputSchema: z.object({
      rule: z.any(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getApproverUserIdsForRule(ctx.client, params.rule);
      return toMcpResult(result);
    }, "Failed: shared_getApproverUserIdsForRule"),
  );

  server.registerTool(
    "shared_getApprovalRuleById",
    {
      description: "get approval rule by id",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getApprovalRuleById(ctx.client, params.id, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: shared_getApprovalRuleById"),
  );

  server.registerTool(
    "shared_getApprovalRules",
    {
      description: "get approval rules",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getApprovalRules(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: shared_getApprovalRules"),
  );

  server.registerTool(
    "shared_getApprovalRulesForApprover",
    {
      description: "get approval rules for approver",
      inputSchema: z.object({
      documentType: z.any(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getApprovalRulesForApprover(ctx.client, params.documentType, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: shared_getApprovalRulesForApprover"),
  );

  server.registerTool(
    "shared_getApprovalsForUser",
    {
      description: "get approvals for user",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0)
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getApprovalsForUser(ctx.client, ctx.userId, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: shared_getApprovalsForUser"),
  );

  server.registerTool(
    "shared_getBase64ImageFromStorage",
    {
      description: "get base64 image from storage",
      inputSchema: z.object({
      path: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getBase64ImageFromStorage(ctx.client, params.path);
      return toMcpResult(result);
    }, "Failed: shared_getBase64ImageFromStorage"),
  );

  server.registerTool(
    "shared_getCountries",
    {
      description: "get countries",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getCountries(ctx.client);
      return toMcpResult(result);
    }, "Failed: shared_getCountries"),
  );

  server.registerTool(
    "shared_getLatestApprovalRequestForDocument",
    {
      description: "get latest approval request for document",
      inputSchema: z.object({
      documentType: z.any(),
      documentId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getLatestApprovalRequestForDocument(ctx.client, params.documentType, params.documentId);
      return toMcpResult(result);
    }, "Failed: shared_getLatestApprovalRequestForDocument"),
  );

  server.registerTool(
    "shared_getModelByItemId",
    {
      description: "get model by item id",
      inputSchema: z.object({
      itemId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getModelByItemId(ctx.client, params.itemId);
      return toMcpResult(result);
    }, "Failed: shared_getModelByItemId"),
  );

  server.registerTool(
    "shared_getNotes",
    {
      description: "get notes",
      inputSchema: z.object({
      documentId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getNotes(ctx.client, params.documentId);
      return toMcpResult(result);
    }, "Failed: shared_getNotes"),
  );

  server.registerTool(
    "shared_getPendingApprovalsForApprover",
    {
      description: "get pending approvals for approver",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPendingApprovalsForApprover(ctx.client, ctx.userId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: shared_getPendingApprovalsForApprover"),
  );

  server.registerTool(
    "shared_getPeriods",
    {
      description: "get periods",
      inputSchema: z.object({
      arg1: z.object({
    startDate: z.string(),
    endDate: z.string()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPeriods(ctx.client, params.arg1);
      return toMcpResult(result);
    }, "Failed: shared_getPeriods"),
  );

  server.registerTool(
    "shared_getSavedViews",
    {
      description: "get saved views",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSavedViews(ctx.client, ctx.userId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: shared_getSavedViews"),
  );

  server.registerTool(
    "shared_getTagsList",
    {
      description: "get tags list",
      inputSchema: z.object({
      table: z.string().nullable().optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getTagsList(ctx.client, ctx.companyId, params.table);
      return toMcpResult(result);
    }, "Failed: shared_getTagsList"),
  );

  server.registerTool(
    "shared_hasPendingApproval",
    {
      description: "has pending approval",
      inputSchema: z.object({
      documentType: z.any(),
      documentId: z.string(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await hasPendingApproval(ctx.client, params.documentType, params.documentId);
      return toMcpResult(result);
    }, "Failed: shared_hasPendingApproval"),
  );

  server.registerTool(
    "shared_importCsv",
    {
      description: "import csv",
      inputSchema: z.object({
      args: z.object({
    table: z.string(),
    filePath: z.string(),
    columnMappings: z.any(),
    enumMappings: z.any().optional()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await importCsv(ctx.client, { ...params.args, companyId: ctx.companyId, userId: ctx.userId });
      return toMcpResult(result);
    }, "Failed: shared_importCsv"),
  );

  server.registerTool(
    "shared_insertNote",
    {
      description: "insert note",
      inputSchema: z.object({
      note: z.object({
    note: z.string(),
    documentId: z.string()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await insertNote(ctx.client, { ...params.note, companyId: ctx.companyId, createdBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: shared_insertNote"),
  );

  server.registerTool(
    "shared_insertTag",
    {
      description: "insert tag",
      inputSchema: z.object({
      tag: z.any(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await insertTag(ctx.client, params.tag);
      return toMcpResult(result);
    }, "Failed: shared_insertTag"),
  );

  server.registerTool(
    "shared_isApprovalRequired",
    {
      description: "is approval required",
      inputSchema: z.object({
      documentType: z.any(),
      amount: z.number().optional(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await isApprovalRequired(ctx.client, params.documentType, ctx.companyId, params.amount);
      return toMcpResult(result);
    }, "Failed: shared_isApprovalRequired"),
  );

  server.registerTool(
    "shared_getExternalLink",
    {
      description: "get external link",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getExternalLink(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: shared_getExternalLink"),
  );

  server.registerTool(
    "shared_upsertExternalLink",
    {
      description: "upsert external link",
      inputSchema: z.object({
      externalLink: z.any(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertExternalLink(ctx.client, params.externalLink);
      return toMcpResult(result);
    }, "Failed: shared_upsertExternalLink"),
  );

  server.registerTool(
    "shared_getCustomerPortals",
    {
      description: "get customer portals",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getCustomerPortals(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: shared_getCustomerPortals"),
  );

  server.registerTool(
    "shared_getCustomerPortal",
    {
      description: "get customer portal",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getCustomerPortal(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: shared_getCustomerPortal"),
  );

  server.registerTool(
    "shared_deleteCustomerPortal",
    {
      description: "delete customer portal",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteCustomerPortal(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: shared_deleteCustomerPortal"),
  );

  server.registerTool(
    "shared_updateModelThumbnail",
    {
      description: "update model thumbnail",
      inputSchema: z.object({
      modelId: z.string(),
      thumbnailPath: z.string(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateModelThumbnail(ctx.client, params.modelId, params.thumbnailPath);
      return toMcpResult(result);
    }, "Failed: shared_updateModelThumbnail"),
  );

  server.registerTool(
    "shared_upsertModelUpload",
    {
      description: "upsert model upload",
      inputSchema: z.object({
      upload: z.any(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertModelUpload(ctx.client, { ...params.upload, companyId: ctx.companyId, createdBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: shared_upsertModelUpload"),
  );

  server.registerTool(
    "shared_updateNote",
    {
      description: "update note",
      inputSchema: z.object({
      id: z.string(),
      note: z.string(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateNote(ctx.client, params.id, params.note);
      return toMcpResult(result);
    }, "Failed: shared_updateNote"),
  );

  server.registerTool(
    "shared_rejectRequest",
    {
      description: "reject request",
      inputSchema: z.object({
      id: z.string(),
      notes: z.string().optional(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await rejectRequest(params.id, ctx.userId, params.notes);
      return toMcpResult(result);
    }, "Failed: shared_rejectRequest"),
  );

  server.registerTool(
    "shared_upsertApprovalRule",
    {
      description: "upsert approval rule",
      inputSchema: z.object({
      rule: z.any(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertApprovalRule(ctx.client, params.rule);
      return toMcpResult(result);
    }, "Failed: shared_upsertApprovalRule"),
  );

  server.registerTool(
    "shared_upsertSavedView",
    {
      description: "upsert saved view",
      inputSchema: z.object({
      view: z.object({
    id: z.string().optional(),
    name: z.string(),
    description: z.string().optional(),
    table: z.string(),
    type: z.enum(["Public", "Private"]),
    filters: z.array(z.string()).optional(),
    sorts: z.array(z.string()).optional(),
    columnPinning: z.any().optional(),
    columnVisibility: z.any().optional(),
    columnOrder: z.array(z.string()).optional()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertSavedView(ctx.client, { ...params.view, companyId: ctx.companyId, userId: ctx.userId });
      return toMcpResult(result);
    }, "Failed: shared_upsertSavedView"),
  );

  server.registerTool(
    "shared_updateSavedViewOrder",
    {
      description: "update saved view order",
      inputSchema: z.object({
      updates: z.object({
    id: z.string(),
    sortOrder: z.number()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateSavedViewOrder(ctx.client, { ...params.updates, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: shared_updateSavedViewOrder"),
  );
};
