ALTER TABLE "apiKeyRateLimit" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "contractorAbility" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "customerContact" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "customerLocation" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "documentFavorite" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "documentLabel" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "documentTransaction" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "employeeShift" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "employeeTypePermission" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "jobFavorite" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "membership" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "purchaseInvoicePaymentRelation" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "purchaseInvoicePriceChange" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "purchaseInvoiceStatusHistory" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "purchaseOrderFavorite" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "purchaseOrderStatusHistory" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "purchaseOrderTransaction" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "purchasingRfqFavorite" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "quoteFavorite" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "quoteLinePrice" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "salesOrderFavorite" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "salesOrderStatusHistory" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "salesOrderTransaction" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "salesRfqFavorite" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "supplierContact" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "supplierLocation" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "supplierQuoteFavorite" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "supplierQuoteLinePrice" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "userAttribute" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "userAttributeValue" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY "apiKeyRateLimit_tenant_select" ON "apiKeyRateLimit" AS PERMISSIVE FOR SELECT TO "carbon_app" USING (EXISTS (SELECT 1 FROM "apiKey" WHERE "apiKey"."id" = "apiKeyRateLimit"."apiKeyId"));--> statement-breakpoint
CREATE POLICY "apiKeyRateLimit_tenant_insert" ON "apiKeyRateLimit" AS PERMISSIVE FOR INSERT TO "carbon_app" WITH CHECK (EXISTS (SELECT 1 FROM "apiKey" WHERE "apiKey"."id" = "apiKeyRateLimit"."apiKeyId"));--> statement-breakpoint
CREATE POLICY "apiKeyRateLimit_tenant_update" ON "apiKeyRateLimit" AS PERMISSIVE FOR UPDATE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "apiKey" WHERE "apiKey"."id" = "apiKeyRateLimit"."apiKeyId")) WITH CHECK (EXISTS (SELECT 1 FROM "apiKey" WHERE "apiKey"."id" = "apiKeyRateLimit"."apiKeyId"));--> statement-breakpoint
CREATE POLICY "apiKeyRateLimit_tenant_delete" ON "apiKeyRateLimit" AS PERMISSIVE FOR DELETE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "apiKey" WHERE "apiKey"."id" = "apiKeyRateLimit"."apiKeyId"));--> statement-breakpoint
CREATE POLICY "contractorAbility_tenant_select" ON "contractorAbility" AS PERMISSIVE FOR SELECT TO "carbon_app" USING (EXISTS (SELECT 1 FROM "ability" WHERE "ability"."id" = "contractorAbility"."abilityId"));--> statement-breakpoint
CREATE POLICY "contractorAbility_tenant_insert" ON "contractorAbility" AS PERMISSIVE FOR INSERT TO "carbon_app" WITH CHECK (EXISTS (SELECT 1 FROM "ability" WHERE "ability"."id" = "contractorAbility"."abilityId"));--> statement-breakpoint
CREATE POLICY "contractorAbility_tenant_update" ON "contractorAbility" AS PERMISSIVE FOR UPDATE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "ability" WHERE "ability"."id" = "contractorAbility"."abilityId")) WITH CHECK (EXISTS (SELECT 1 FROM "ability" WHERE "ability"."id" = "contractorAbility"."abilityId"));--> statement-breakpoint
CREATE POLICY "contractorAbility_tenant_delete" ON "contractorAbility" AS PERMISSIVE FOR DELETE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "ability" WHERE "ability"."id" = "contractorAbility"."abilityId"));--> statement-breakpoint
CREATE POLICY "customerContact_tenant_select" ON "customerContact" AS PERMISSIVE FOR SELECT TO "carbon_app" USING (EXISTS (SELECT 1 FROM "contact" WHERE "contact"."id" = "customerContact"."contactId"));--> statement-breakpoint
CREATE POLICY "customerContact_tenant_insert" ON "customerContact" AS PERMISSIVE FOR INSERT TO "carbon_app" WITH CHECK (EXISTS (SELECT 1 FROM "contact" WHERE "contact"."id" = "customerContact"."contactId"));--> statement-breakpoint
CREATE POLICY "customerContact_tenant_update" ON "customerContact" AS PERMISSIVE FOR UPDATE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "contact" WHERE "contact"."id" = "customerContact"."contactId")) WITH CHECK (EXISTS (SELECT 1 FROM "contact" WHERE "contact"."id" = "customerContact"."contactId"));--> statement-breakpoint
CREATE POLICY "customerContact_tenant_delete" ON "customerContact" AS PERMISSIVE FOR DELETE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "contact" WHERE "contact"."id" = "customerContact"."contactId"));--> statement-breakpoint
CREATE POLICY "customerLocation_tenant_select" ON "customerLocation" AS PERMISSIVE FOR SELECT TO "carbon_app" USING (EXISTS (SELECT 1 FROM "address" WHERE "address"."id" = "customerLocation"."addressId"));--> statement-breakpoint
CREATE POLICY "customerLocation_tenant_insert" ON "customerLocation" AS PERMISSIVE FOR INSERT TO "carbon_app" WITH CHECK (EXISTS (SELECT 1 FROM "address" WHERE "address"."id" = "customerLocation"."addressId"));--> statement-breakpoint
CREATE POLICY "customerLocation_tenant_update" ON "customerLocation" AS PERMISSIVE FOR UPDATE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "address" WHERE "address"."id" = "customerLocation"."addressId")) WITH CHECK (EXISTS (SELECT 1 FROM "address" WHERE "address"."id" = "customerLocation"."addressId"));--> statement-breakpoint
CREATE POLICY "customerLocation_tenant_delete" ON "customerLocation" AS PERMISSIVE FOR DELETE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "address" WHERE "address"."id" = "customerLocation"."addressId"));--> statement-breakpoint
CREATE POLICY "documentFavorite_tenant_select" ON "documentFavorite" AS PERMISSIVE FOR SELECT TO "carbon_app" USING (EXISTS (SELECT 1 FROM "document" WHERE "document"."id" = "documentFavorite"."documentId"));--> statement-breakpoint
CREATE POLICY "documentFavorite_tenant_insert" ON "documentFavorite" AS PERMISSIVE FOR INSERT TO "carbon_app" WITH CHECK (EXISTS (SELECT 1 FROM "document" WHERE "document"."id" = "documentFavorite"."documentId"));--> statement-breakpoint
CREATE POLICY "documentFavorite_tenant_update" ON "documentFavorite" AS PERMISSIVE FOR UPDATE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "document" WHERE "document"."id" = "documentFavorite"."documentId")) WITH CHECK (EXISTS (SELECT 1 FROM "document" WHERE "document"."id" = "documentFavorite"."documentId"));--> statement-breakpoint
CREATE POLICY "documentFavorite_tenant_delete" ON "documentFavorite" AS PERMISSIVE FOR DELETE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "document" WHERE "document"."id" = "documentFavorite"."documentId"));--> statement-breakpoint
CREATE POLICY "documentLabel_tenant_select" ON "documentLabel" AS PERMISSIVE FOR SELECT TO "carbon_app" USING (EXISTS (SELECT 1 FROM "document" WHERE "document"."id" = "documentLabel"."documentId"));--> statement-breakpoint
CREATE POLICY "documentLabel_tenant_insert" ON "documentLabel" AS PERMISSIVE FOR INSERT TO "carbon_app" WITH CHECK (EXISTS (SELECT 1 FROM "document" WHERE "document"."id" = "documentLabel"."documentId"));--> statement-breakpoint
CREATE POLICY "documentLabel_tenant_update" ON "documentLabel" AS PERMISSIVE FOR UPDATE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "document" WHERE "document"."id" = "documentLabel"."documentId")) WITH CHECK (EXISTS (SELECT 1 FROM "document" WHERE "document"."id" = "documentLabel"."documentId"));--> statement-breakpoint
CREATE POLICY "documentLabel_tenant_delete" ON "documentLabel" AS PERMISSIVE FOR DELETE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "document" WHERE "document"."id" = "documentLabel"."documentId"));--> statement-breakpoint
CREATE POLICY "documentTransaction_tenant_select" ON "documentTransaction" AS PERMISSIVE FOR SELECT TO "carbon_app" USING (EXISTS (SELECT 1 FROM "document" WHERE "document"."id" = "documentTransaction"."documentId"));--> statement-breakpoint
CREATE POLICY "documentTransaction_tenant_insert" ON "documentTransaction" AS PERMISSIVE FOR INSERT TO "carbon_app" WITH CHECK (EXISTS (SELECT 1 FROM "document" WHERE "document"."id" = "documentTransaction"."documentId"));--> statement-breakpoint
CREATE POLICY "documentTransaction_tenant_update" ON "documentTransaction" AS PERMISSIVE FOR UPDATE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "document" WHERE "document"."id" = "documentTransaction"."documentId")) WITH CHECK (EXISTS (SELECT 1 FROM "document" WHERE "document"."id" = "documentTransaction"."documentId"));--> statement-breakpoint
CREATE POLICY "documentTransaction_tenant_delete" ON "documentTransaction" AS PERMISSIVE FOR DELETE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "document" WHERE "document"."id" = "documentTransaction"."documentId"));--> statement-breakpoint
CREATE POLICY "employeeShift_tenant_select" ON "employeeShift" AS PERMISSIVE FOR SELECT TO "carbon_app" USING (EXISTS (SELECT 1 FROM "shift" WHERE "shift"."id" = "employeeShift"."shiftId"));--> statement-breakpoint
CREATE POLICY "employeeShift_tenant_insert" ON "employeeShift" AS PERMISSIVE FOR INSERT TO "carbon_app" WITH CHECK (EXISTS (SELECT 1 FROM "shift" WHERE "shift"."id" = "employeeShift"."shiftId"));--> statement-breakpoint
CREATE POLICY "employeeShift_tenant_update" ON "employeeShift" AS PERMISSIVE FOR UPDATE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "shift" WHERE "shift"."id" = "employeeShift"."shiftId")) WITH CHECK (EXISTS (SELECT 1 FROM "shift" WHERE "shift"."id" = "employeeShift"."shiftId"));--> statement-breakpoint
CREATE POLICY "employeeShift_tenant_delete" ON "employeeShift" AS PERMISSIVE FOR DELETE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "shift" WHERE "shift"."id" = "employeeShift"."shiftId"));--> statement-breakpoint
CREATE POLICY "employeeTypePermission_tenant_select" ON "employeeTypePermission" AS PERMISSIVE FOR SELECT TO "carbon_app" USING (EXISTS (SELECT 1 FROM "employeeType" WHERE "employeeType"."id" = "employeeTypePermission"."employeeTypeId"));--> statement-breakpoint
CREATE POLICY "employeeTypePermission_tenant_insert" ON "employeeTypePermission" AS PERMISSIVE FOR INSERT TO "carbon_app" WITH CHECK (EXISTS (SELECT 1 FROM "employeeType" WHERE "employeeType"."id" = "employeeTypePermission"."employeeTypeId"));--> statement-breakpoint
CREATE POLICY "employeeTypePermission_tenant_update" ON "employeeTypePermission" AS PERMISSIVE FOR UPDATE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "employeeType" WHERE "employeeType"."id" = "employeeTypePermission"."employeeTypeId")) WITH CHECK (EXISTS (SELECT 1 FROM "employeeType" WHERE "employeeType"."id" = "employeeTypePermission"."employeeTypeId"));--> statement-breakpoint
CREATE POLICY "employeeTypePermission_tenant_delete" ON "employeeTypePermission" AS PERMISSIVE FOR DELETE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "employeeType" WHERE "employeeType"."id" = "employeeTypePermission"."employeeTypeId"));--> statement-breakpoint
CREATE POLICY "jobFavorite_tenant_select" ON "jobFavorite" AS PERMISSIVE FOR SELECT TO "carbon_app" USING (EXISTS (SELECT 1 FROM "job" WHERE "job"."id" = "jobFavorite"."jobId"));--> statement-breakpoint
CREATE POLICY "jobFavorite_tenant_insert" ON "jobFavorite" AS PERMISSIVE FOR INSERT TO "carbon_app" WITH CHECK (EXISTS (SELECT 1 FROM "job" WHERE "job"."id" = "jobFavorite"."jobId"));--> statement-breakpoint
CREATE POLICY "jobFavorite_tenant_update" ON "jobFavorite" AS PERMISSIVE FOR UPDATE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "job" WHERE "job"."id" = "jobFavorite"."jobId")) WITH CHECK (EXISTS (SELECT 1 FROM "job" WHERE "job"."id" = "jobFavorite"."jobId"));--> statement-breakpoint
CREATE POLICY "jobFavorite_tenant_delete" ON "jobFavorite" AS PERMISSIVE FOR DELETE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "job" WHERE "job"."id" = "jobFavorite"."jobId"));--> statement-breakpoint
CREATE POLICY "membership_tenant_select" ON "membership" AS PERMISSIVE FOR SELECT TO "carbon_app" USING (EXISTS (SELECT 1 FROM "group" WHERE "group"."id" = "membership"."groupId"));--> statement-breakpoint
CREATE POLICY "membership_tenant_insert" ON "membership" AS PERMISSIVE FOR INSERT TO "carbon_app" WITH CHECK (EXISTS (SELECT 1 FROM "group" WHERE "group"."id" = "membership"."groupId"));--> statement-breakpoint
CREATE POLICY "membership_tenant_update" ON "membership" AS PERMISSIVE FOR UPDATE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "group" WHERE "group"."id" = "membership"."groupId")) WITH CHECK (EXISTS (SELECT 1 FROM "group" WHERE "group"."id" = "membership"."groupId"));--> statement-breakpoint
CREATE POLICY "membership_tenant_delete" ON "membership" AS PERMISSIVE FOR DELETE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "group" WHERE "group"."id" = "membership"."groupId"));--> statement-breakpoint
CREATE POLICY "purchaseInvoicePaymentRelation_tenant_select" ON "purchaseInvoicePaymentRelation" AS PERMISSIVE FOR SELECT TO "carbon_app" USING (EXISTS (SELECT 1 FROM "purchaseInvoice" WHERE "purchaseInvoice"."id" = "purchaseInvoicePaymentRelation"."invoiceId"));--> statement-breakpoint
CREATE POLICY "purchaseInvoicePaymentRelation_tenant_insert" ON "purchaseInvoicePaymentRelation" AS PERMISSIVE FOR INSERT TO "carbon_app" WITH CHECK (EXISTS (SELECT 1 FROM "purchaseInvoice" WHERE "purchaseInvoice"."id" = "purchaseInvoicePaymentRelation"."invoiceId"));--> statement-breakpoint
CREATE POLICY "purchaseInvoicePaymentRelation_tenant_update" ON "purchaseInvoicePaymentRelation" AS PERMISSIVE FOR UPDATE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "purchaseInvoice" WHERE "purchaseInvoice"."id" = "purchaseInvoicePaymentRelation"."invoiceId")) WITH CHECK (EXISTS (SELECT 1 FROM "purchaseInvoice" WHERE "purchaseInvoice"."id" = "purchaseInvoicePaymentRelation"."invoiceId"));--> statement-breakpoint
CREATE POLICY "purchaseInvoicePaymentRelation_tenant_delete" ON "purchaseInvoicePaymentRelation" AS PERMISSIVE FOR DELETE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "purchaseInvoice" WHERE "purchaseInvoice"."id" = "purchaseInvoicePaymentRelation"."invoiceId"));--> statement-breakpoint
CREATE POLICY "purchaseInvoicePriceChange_tenant_select" ON "purchaseInvoicePriceChange" AS PERMISSIVE FOR SELECT TO "carbon_app" USING (EXISTS (SELECT 1 FROM "purchaseInvoice" WHERE "purchaseInvoice"."id" = "purchaseInvoicePriceChange"."invoiceId"));--> statement-breakpoint
CREATE POLICY "purchaseInvoicePriceChange_tenant_insert" ON "purchaseInvoicePriceChange" AS PERMISSIVE FOR INSERT TO "carbon_app" WITH CHECK (EXISTS (SELECT 1 FROM "purchaseInvoice" WHERE "purchaseInvoice"."id" = "purchaseInvoicePriceChange"."invoiceId"));--> statement-breakpoint
CREATE POLICY "purchaseInvoicePriceChange_tenant_update" ON "purchaseInvoicePriceChange" AS PERMISSIVE FOR UPDATE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "purchaseInvoice" WHERE "purchaseInvoice"."id" = "purchaseInvoicePriceChange"."invoiceId")) WITH CHECK (EXISTS (SELECT 1 FROM "purchaseInvoice" WHERE "purchaseInvoice"."id" = "purchaseInvoicePriceChange"."invoiceId"));--> statement-breakpoint
CREATE POLICY "purchaseInvoicePriceChange_tenant_delete" ON "purchaseInvoicePriceChange" AS PERMISSIVE FOR DELETE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "purchaseInvoice" WHERE "purchaseInvoice"."id" = "purchaseInvoicePriceChange"."invoiceId"));--> statement-breakpoint
CREATE POLICY "purchaseInvoiceStatusHistory_tenant_select" ON "purchaseInvoiceStatusHistory" AS PERMISSIVE FOR SELECT TO "carbon_app" USING (EXISTS (SELECT 1 FROM "purchaseInvoice" WHERE "purchaseInvoice"."id" = "purchaseInvoiceStatusHistory"."invoiceId"));--> statement-breakpoint
CREATE POLICY "purchaseInvoiceStatusHistory_tenant_insert" ON "purchaseInvoiceStatusHistory" AS PERMISSIVE FOR INSERT TO "carbon_app" WITH CHECK (EXISTS (SELECT 1 FROM "purchaseInvoice" WHERE "purchaseInvoice"."id" = "purchaseInvoiceStatusHistory"."invoiceId"));--> statement-breakpoint
CREATE POLICY "purchaseInvoiceStatusHistory_tenant_update" ON "purchaseInvoiceStatusHistory" AS PERMISSIVE FOR UPDATE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "purchaseInvoice" WHERE "purchaseInvoice"."id" = "purchaseInvoiceStatusHistory"."invoiceId")) WITH CHECK (EXISTS (SELECT 1 FROM "purchaseInvoice" WHERE "purchaseInvoice"."id" = "purchaseInvoiceStatusHistory"."invoiceId"));--> statement-breakpoint
CREATE POLICY "purchaseInvoiceStatusHistory_tenant_delete" ON "purchaseInvoiceStatusHistory" AS PERMISSIVE FOR DELETE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "purchaseInvoice" WHERE "purchaseInvoice"."id" = "purchaseInvoiceStatusHistory"."invoiceId"));--> statement-breakpoint
CREATE POLICY "purchaseOrderFavorite_tenant_select" ON "purchaseOrderFavorite" AS PERMISSIVE FOR SELECT TO "carbon_app" USING (EXISTS (SELECT 1 FROM "purchaseOrder" WHERE "purchaseOrder"."id" = "purchaseOrderFavorite"."purchaseOrderId"));--> statement-breakpoint
CREATE POLICY "purchaseOrderFavorite_tenant_insert" ON "purchaseOrderFavorite" AS PERMISSIVE FOR INSERT TO "carbon_app" WITH CHECK (EXISTS (SELECT 1 FROM "purchaseOrder" WHERE "purchaseOrder"."id" = "purchaseOrderFavorite"."purchaseOrderId"));--> statement-breakpoint
CREATE POLICY "purchaseOrderFavorite_tenant_update" ON "purchaseOrderFavorite" AS PERMISSIVE FOR UPDATE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "purchaseOrder" WHERE "purchaseOrder"."id" = "purchaseOrderFavorite"."purchaseOrderId")) WITH CHECK (EXISTS (SELECT 1 FROM "purchaseOrder" WHERE "purchaseOrder"."id" = "purchaseOrderFavorite"."purchaseOrderId"));--> statement-breakpoint
CREATE POLICY "purchaseOrderFavorite_tenant_delete" ON "purchaseOrderFavorite" AS PERMISSIVE FOR DELETE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "purchaseOrder" WHERE "purchaseOrder"."id" = "purchaseOrderFavorite"."purchaseOrderId"));--> statement-breakpoint
CREATE POLICY "purchaseOrderStatusHistory_tenant_select" ON "purchaseOrderStatusHistory" AS PERMISSIVE FOR SELECT TO "carbon_app" USING (EXISTS (SELECT 1 FROM "purchaseOrder" WHERE "purchaseOrder"."id" = "purchaseOrderStatusHistory"."purchaseOrderId"));--> statement-breakpoint
CREATE POLICY "purchaseOrderStatusHistory_tenant_insert" ON "purchaseOrderStatusHistory" AS PERMISSIVE FOR INSERT TO "carbon_app" WITH CHECK (EXISTS (SELECT 1 FROM "purchaseOrder" WHERE "purchaseOrder"."id" = "purchaseOrderStatusHistory"."purchaseOrderId"));--> statement-breakpoint
CREATE POLICY "purchaseOrderStatusHistory_tenant_update" ON "purchaseOrderStatusHistory" AS PERMISSIVE FOR UPDATE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "purchaseOrder" WHERE "purchaseOrder"."id" = "purchaseOrderStatusHistory"."purchaseOrderId")) WITH CHECK (EXISTS (SELECT 1 FROM "purchaseOrder" WHERE "purchaseOrder"."id" = "purchaseOrderStatusHistory"."purchaseOrderId"));--> statement-breakpoint
CREATE POLICY "purchaseOrderStatusHistory_tenant_delete" ON "purchaseOrderStatusHistory" AS PERMISSIVE FOR DELETE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "purchaseOrder" WHERE "purchaseOrder"."id" = "purchaseOrderStatusHistory"."purchaseOrderId"));--> statement-breakpoint
CREATE POLICY "purchaseOrderTransaction_tenant_select" ON "purchaseOrderTransaction" AS PERMISSIVE FOR SELECT TO "carbon_app" USING (EXISTS (SELECT 1 FROM "purchaseOrder" WHERE "purchaseOrder"."id" = "purchaseOrderTransaction"."purchaseOrderId"));--> statement-breakpoint
CREATE POLICY "purchaseOrderTransaction_tenant_insert" ON "purchaseOrderTransaction" AS PERMISSIVE FOR INSERT TO "carbon_app" WITH CHECK (EXISTS (SELECT 1 FROM "purchaseOrder" WHERE "purchaseOrder"."id" = "purchaseOrderTransaction"."purchaseOrderId"));--> statement-breakpoint
CREATE POLICY "purchaseOrderTransaction_tenant_update" ON "purchaseOrderTransaction" AS PERMISSIVE FOR UPDATE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "purchaseOrder" WHERE "purchaseOrder"."id" = "purchaseOrderTransaction"."purchaseOrderId")) WITH CHECK (EXISTS (SELECT 1 FROM "purchaseOrder" WHERE "purchaseOrder"."id" = "purchaseOrderTransaction"."purchaseOrderId"));--> statement-breakpoint
CREATE POLICY "purchaseOrderTransaction_tenant_delete" ON "purchaseOrderTransaction" AS PERMISSIVE FOR DELETE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "purchaseOrder" WHERE "purchaseOrder"."id" = "purchaseOrderTransaction"."purchaseOrderId"));--> statement-breakpoint
CREATE POLICY "purchasingRfqFavorite_tenant_select" ON "purchasingRfqFavorite" AS PERMISSIVE FOR SELECT TO "carbon_app" USING (EXISTS (SELECT 1 FROM "purchasingRfq" WHERE "purchasingRfq"."id" = "purchasingRfqFavorite"."rfqId"));--> statement-breakpoint
CREATE POLICY "purchasingRfqFavorite_tenant_insert" ON "purchasingRfqFavorite" AS PERMISSIVE FOR INSERT TO "carbon_app" WITH CHECK (EXISTS (SELECT 1 FROM "purchasingRfq" WHERE "purchasingRfq"."id" = "purchasingRfqFavorite"."rfqId"));--> statement-breakpoint
CREATE POLICY "purchasingRfqFavorite_tenant_update" ON "purchasingRfqFavorite" AS PERMISSIVE FOR UPDATE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "purchasingRfq" WHERE "purchasingRfq"."id" = "purchasingRfqFavorite"."rfqId")) WITH CHECK (EXISTS (SELECT 1 FROM "purchasingRfq" WHERE "purchasingRfq"."id" = "purchasingRfqFavorite"."rfqId"));--> statement-breakpoint
CREATE POLICY "purchasingRfqFavorite_tenant_delete" ON "purchasingRfqFavorite" AS PERMISSIVE FOR DELETE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "purchasingRfq" WHERE "purchasingRfq"."id" = "purchasingRfqFavorite"."rfqId"));--> statement-breakpoint
CREATE POLICY "quoteFavorite_tenant_select" ON "quoteFavorite" AS PERMISSIVE FOR SELECT TO "carbon_app" USING (EXISTS (SELECT 1 FROM "quote" WHERE "quote"."id" = "quoteFavorite"."quoteId"));--> statement-breakpoint
CREATE POLICY "quoteFavorite_tenant_insert" ON "quoteFavorite" AS PERMISSIVE FOR INSERT TO "carbon_app" WITH CHECK (EXISTS (SELECT 1 FROM "quote" WHERE "quote"."id" = "quoteFavorite"."quoteId"));--> statement-breakpoint
CREATE POLICY "quoteFavorite_tenant_update" ON "quoteFavorite" AS PERMISSIVE FOR UPDATE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "quote" WHERE "quote"."id" = "quoteFavorite"."quoteId")) WITH CHECK (EXISTS (SELECT 1 FROM "quote" WHERE "quote"."id" = "quoteFavorite"."quoteId"));--> statement-breakpoint
CREATE POLICY "quoteFavorite_tenant_delete" ON "quoteFavorite" AS PERMISSIVE FOR DELETE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "quote" WHERE "quote"."id" = "quoteFavorite"."quoteId"));--> statement-breakpoint
CREATE POLICY "quoteLinePrice_tenant_select" ON "quoteLinePrice" AS PERMISSIVE FOR SELECT TO "carbon_app" USING (EXISTS (SELECT 1 FROM "quote" WHERE "quote"."id" = "quoteLinePrice"."quoteId"));--> statement-breakpoint
CREATE POLICY "quoteLinePrice_tenant_insert" ON "quoteLinePrice" AS PERMISSIVE FOR INSERT TO "carbon_app" WITH CHECK (EXISTS (SELECT 1 FROM "quote" WHERE "quote"."id" = "quoteLinePrice"."quoteId"));--> statement-breakpoint
CREATE POLICY "quoteLinePrice_tenant_update" ON "quoteLinePrice" AS PERMISSIVE FOR UPDATE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "quote" WHERE "quote"."id" = "quoteLinePrice"."quoteId")) WITH CHECK (EXISTS (SELECT 1 FROM "quote" WHERE "quote"."id" = "quoteLinePrice"."quoteId"));--> statement-breakpoint
CREATE POLICY "quoteLinePrice_tenant_delete" ON "quoteLinePrice" AS PERMISSIVE FOR DELETE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "quote" WHERE "quote"."id" = "quoteLinePrice"."quoteId"));--> statement-breakpoint
CREATE POLICY "salesOrderFavorite_tenant_select" ON "salesOrderFavorite" AS PERMISSIVE FOR SELECT TO "carbon_app" USING (EXISTS (SELECT 1 FROM "salesOrder" WHERE "salesOrder"."id" = "salesOrderFavorite"."salesOrderId"));--> statement-breakpoint
CREATE POLICY "salesOrderFavorite_tenant_insert" ON "salesOrderFavorite" AS PERMISSIVE FOR INSERT TO "carbon_app" WITH CHECK (EXISTS (SELECT 1 FROM "salesOrder" WHERE "salesOrder"."id" = "salesOrderFavorite"."salesOrderId"));--> statement-breakpoint
CREATE POLICY "salesOrderFavorite_tenant_update" ON "salesOrderFavorite" AS PERMISSIVE FOR UPDATE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "salesOrder" WHERE "salesOrder"."id" = "salesOrderFavorite"."salesOrderId")) WITH CHECK (EXISTS (SELECT 1 FROM "salesOrder" WHERE "salesOrder"."id" = "salesOrderFavorite"."salesOrderId"));--> statement-breakpoint
CREATE POLICY "salesOrderFavorite_tenant_delete" ON "salesOrderFavorite" AS PERMISSIVE FOR DELETE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "salesOrder" WHERE "salesOrder"."id" = "salesOrderFavorite"."salesOrderId"));--> statement-breakpoint
CREATE POLICY "salesOrderStatusHistory_tenant_select" ON "salesOrderStatusHistory" AS PERMISSIVE FOR SELECT TO "carbon_app" USING (EXISTS (SELECT 1 FROM "salesOrder" WHERE "salesOrder"."id" = "salesOrderStatusHistory"."salesOrderId"));--> statement-breakpoint
CREATE POLICY "salesOrderStatusHistory_tenant_insert" ON "salesOrderStatusHistory" AS PERMISSIVE FOR INSERT TO "carbon_app" WITH CHECK (EXISTS (SELECT 1 FROM "salesOrder" WHERE "salesOrder"."id" = "salesOrderStatusHistory"."salesOrderId"));--> statement-breakpoint
CREATE POLICY "salesOrderStatusHistory_tenant_update" ON "salesOrderStatusHistory" AS PERMISSIVE FOR UPDATE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "salesOrder" WHERE "salesOrder"."id" = "salesOrderStatusHistory"."salesOrderId")) WITH CHECK (EXISTS (SELECT 1 FROM "salesOrder" WHERE "salesOrder"."id" = "salesOrderStatusHistory"."salesOrderId"));--> statement-breakpoint
CREATE POLICY "salesOrderStatusHistory_tenant_delete" ON "salesOrderStatusHistory" AS PERMISSIVE FOR DELETE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "salesOrder" WHERE "salesOrder"."id" = "salesOrderStatusHistory"."salesOrderId"));--> statement-breakpoint
CREATE POLICY "salesOrderTransaction_tenant_select" ON "salesOrderTransaction" AS PERMISSIVE FOR SELECT TO "carbon_app" USING (EXISTS (SELECT 1 FROM "salesOrder" WHERE "salesOrder"."id" = "salesOrderTransaction"."salesOrderId"));--> statement-breakpoint
CREATE POLICY "salesOrderTransaction_tenant_insert" ON "salesOrderTransaction" AS PERMISSIVE FOR INSERT TO "carbon_app" WITH CHECK (EXISTS (SELECT 1 FROM "salesOrder" WHERE "salesOrder"."id" = "salesOrderTransaction"."salesOrderId"));--> statement-breakpoint
CREATE POLICY "salesOrderTransaction_tenant_update" ON "salesOrderTransaction" AS PERMISSIVE FOR UPDATE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "salesOrder" WHERE "salesOrder"."id" = "salesOrderTransaction"."salesOrderId")) WITH CHECK (EXISTS (SELECT 1 FROM "salesOrder" WHERE "salesOrder"."id" = "salesOrderTransaction"."salesOrderId"));--> statement-breakpoint
CREATE POLICY "salesOrderTransaction_tenant_delete" ON "salesOrderTransaction" AS PERMISSIVE FOR DELETE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "salesOrder" WHERE "salesOrder"."id" = "salesOrderTransaction"."salesOrderId"));--> statement-breakpoint
CREATE POLICY "salesRfqFavorite_tenant_select" ON "salesRfqFavorite" AS PERMISSIVE FOR SELECT TO "carbon_app" USING (EXISTS (SELECT 1 FROM "salesRfq" WHERE "salesRfq"."id" = "salesRfqFavorite"."rfqId"));--> statement-breakpoint
CREATE POLICY "salesRfqFavorite_tenant_insert" ON "salesRfqFavorite" AS PERMISSIVE FOR INSERT TO "carbon_app" WITH CHECK (EXISTS (SELECT 1 FROM "salesRfq" WHERE "salesRfq"."id" = "salesRfqFavorite"."rfqId"));--> statement-breakpoint
CREATE POLICY "salesRfqFavorite_tenant_update" ON "salesRfqFavorite" AS PERMISSIVE FOR UPDATE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "salesRfq" WHERE "salesRfq"."id" = "salesRfqFavorite"."rfqId")) WITH CHECK (EXISTS (SELECT 1 FROM "salesRfq" WHERE "salesRfq"."id" = "salesRfqFavorite"."rfqId"));--> statement-breakpoint
CREATE POLICY "salesRfqFavorite_tenant_delete" ON "salesRfqFavorite" AS PERMISSIVE FOR DELETE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "salesRfq" WHERE "salesRfq"."id" = "salesRfqFavorite"."rfqId"));--> statement-breakpoint
CREATE POLICY "supplierContact_tenant_select" ON "supplierContact" AS PERMISSIVE FOR SELECT TO "carbon_app" USING (EXISTS (SELECT 1 FROM "contact" WHERE "contact"."id" = "supplierContact"."contactId"));--> statement-breakpoint
CREATE POLICY "supplierContact_tenant_insert" ON "supplierContact" AS PERMISSIVE FOR INSERT TO "carbon_app" WITH CHECK (EXISTS (SELECT 1 FROM "contact" WHERE "contact"."id" = "supplierContact"."contactId"));--> statement-breakpoint
CREATE POLICY "supplierContact_tenant_update" ON "supplierContact" AS PERMISSIVE FOR UPDATE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "contact" WHERE "contact"."id" = "supplierContact"."contactId")) WITH CHECK (EXISTS (SELECT 1 FROM "contact" WHERE "contact"."id" = "supplierContact"."contactId"));--> statement-breakpoint
CREATE POLICY "supplierContact_tenant_delete" ON "supplierContact" AS PERMISSIVE FOR DELETE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "contact" WHERE "contact"."id" = "supplierContact"."contactId"));--> statement-breakpoint
CREATE POLICY "supplierLocation_tenant_select" ON "supplierLocation" AS PERMISSIVE FOR SELECT TO "carbon_app" USING (EXISTS (SELECT 1 FROM "address" WHERE "address"."id" = "supplierLocation"."addressId"));--> statement-breakpoint
CREATE POLICY "supplierLocation_tenant_insert" ON "supplierLocation" AS PERMISSIVE FOR INSERT TO "carbon_app" WITH CHECK (EXISTS (SELECT 1 FROM "address" WHERE "address"."id" = "supplierLocation"."addressId"));--> statement-breakpoint
CREATE POLICY "supplierLocation_tenant_update" ON "supplierLocation" AS PERMISSIVE FOR UPDATE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "address" WHERE "address"."id" = "supplierLocation"."addressId")) WITH CHECK (EXISTS (SELECT 1 FROM "address" WHERE "address"."id" = "supplierLocation"."addressId"));--> statement-breakpoint
CREATE POLICY "supplierLocation_tenant_delete" ON "supplierLocation" AS PERMISSIVE FOR DELETE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "address" WHERE "address"."id" = "supplierLocation"."addressId"));--> statement-breakpoint
CREATE POLICY "supplierQuoteFavorite_tenant_select" ON "supplierQuoteFavorite" AS PERMISSIVE FOR SELECT TO "carbon_app" USING (EXISTS (SELECT 1 FROM "supplierQuote" WHERE "supplierQuote"."id" = "supplierQuoteFavorite"."supplierQuoteId"));--> statement-breakpoint
CREATE POLICY "supplierQuoteFavorite_tenant_insert" ON "supplierQuoteFavorite" AS PERMISSIVE FOR INSERT TO "carbon_app" WITH CHECK (EXISTS (SELECT 1 FROM "supplierQuote" WHERE "supplierQuote"."id" = "supplierQuoteFavorite"."supplierQuoteId"));--> statement-breakpoint
CREATE POLICY "supplierQuoteFavorite_tenant_update" ON "supplierQuoteFavorite" AS PERMISSIVE FOR UPDATE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "supplierQuote" WHERE "supplierQuote"."id" = "supplierQuoteFavorite"."supplierQuoteId")) WITH CHECK (EXISTS (SELECT 1 FROM "supplierQuote" WHERE "supplierQuote"."id" = "supplierQuoteFavorite"."supplierQuoteId"));--> statement-breakpoint
CREATE POLICY "supplierQuoteFavorite_tenant_delete" ON "supplierQuoteFavorite" AS PERMISSIVE FOR DELETE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "supplierQuote" WHERE "supplierQuote"."id" = "supplierQuoteFavorite"."supplierQuoteId"));--> statement-breakpoint
CREATE POLICY "supplierQuoteLinePrice_tenant_select" ON "supplierQuoteLinePrice" AS PERMISSIVE FOR SELECT TO "carbon_app" USING (EXISTS (SELECT 1 FROM "supplierQuote" WHERE "supplierQuote"."id" = "supplierQuoteLinePrice"."supplierQuoteId"));--> statement-breakpoint
CREATE POLICY "supplierQuoteLinePrice_tenant_insert" ON "supplierQuoteLinePrice" AS PERMISSIVE FOR INSERT TO "carbon_app" WITH CHECK (EXISTS (SELECT 1 FROM "supplierQuote" WHERE "supplierQuote"."id" = "supplierQuoteLinePrice"."supplierQuoteId"));--> statement-breakpoint
CREATE POLICY "supplierQuoteLinePrice_tenant_update" ON "supplierQuoteLinePrice" AS PERMISSIVE FOR UPDATE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "supplierQuote" WHERE "supplierQuote"."id" = "supplierQuoteLinePrice"."supplierQuoteId")) WITH CHECK (EXISTS (SELECT 1 FROM "supplierQuote" WHERE "supplierQuote"."id" = "supplierQuoteLinePrice"."supplierQuoteId"));--> statement-breakpoint
CREATE POLICY "supplierQuoteLinePrice_tenant_delete" ON "supplierQuoteLinePrice" AS PERMISSIVE FOR DELETE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "supplierQuote" WHERE "supplierQuote"."id" = "supplierQuoteLinePrice"."supplierQuoteId"));--> statement-breakpoint
CREATE POLICY "userAttribute_tenant_select" ON "userAttribute" AS PERMISSIVE FOR SELECT TO "carbon_app" USING (EXISTS (SELECT 1 FROM "userAttributeCategory" WHERE "userAttributeCategory"."id" = "userAttribute"."userAttributeCategoryId"));--> statement-breakpoint
CREATE POLICY "userAttribute_tenant_insert" ON "userAttribute" AS PERMISSIVE FOR INSERT TO "carbon_app" WITH CHECK (EXISTS (SELECT 1 FROM "userAttributeCategory" WHERE "userAttributeCategory"."id" = "userAttribute"."userAttributeCategoryId"));--> statement-breakpoint
CREATE POLICY "userAttribute_tenant_update" ON "userAttribute" AS PERMISSIVE FOR UPDATE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "userAttributeCategory" WHERE "userAttributeCategory"."id" = "userAttribute"."userAttributeCategoryId")) WITH CHECK (EXISTS (SELECT 1 FROM "userAttributeCategory" WHERE "userAttributeCategory"."id" = "userAttribute"."userAttributeCategoryId"));--> statement-breakpoint
CREATE POLICY "userAttribute_tenant_delete" ON "userAttribute" AS PERMISSIVE FOR DELETE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "userAttributeCategory" WHERE "userAttributeCategory"."id" = "userAttribute"."userAttributeCategoryId"));--> statement-breakpoint
CREATE POLICY "userAttributeValue_tenant_select" ON "userAttributeValue" AS PERMISSIVE FOR SELECT TO "carbon_app" USING (EXISTS (SELECT 1 FROM "userAttribute" WHERE "userAttribute"."id" = "userAttributeValue"."userAttributeId"));--> statement-breakpoint
CREATE POLICY "userAttributeValue_tenant_insert" ON "userAttributeValue" AS PERMISSIVE FOR INSERT TO "carbon_app" WITH CHECK (EXISTS (SELECT 1 FROM "userAttribute" WHERE "userAttribute"."id" = "userAttributeValue"."userAttributeId"));--> statement-breakpoint
CREATE POLICY "userAttributeValue_tenant_update" ON "userAttributeValue" AS PERMISSIVE FOR UPDATE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "userAttribute" WHERE "userAttribute"."id" = "userAttributeValue"."userAttributeId")) WITH CHECK (EXISTS (SELECT 1 FROM "userAttribute" WHERE "userAttribute"."id" = "userAttributeValue"."userAttributeId"));--> statement-breakpoint
CREATE POLICY "userAttributeValue_tenant_delete" ON "userAttributeValue" AS PERMISSIVE FOR DELETE TO "carbon_app" USING (EXISTS (SELECT 1 FROM "userAttribute" WHERE "userAttribute"."id" = "userAttributeValue"."userAttributeId"));