import { existsSync, unlinkSync, writeFileSync } from "node:fs";
import { join } from "pathe";
import { APP_CHOICES } from "./constants.js";
import { type AuthSecret, type PortMap, SHARED_REDIS_PORT } from "./worktree.js";

export function renderEnv(opts: {
  slug: string;
  ports: PortMap;
  redisDb: number;
  auth: AuthSecret;
  /** When true, write portless hostnames; when false, write http://localhost:PORT URLs. */
  portless: boolean;
  /** Required when portless is true. e.g. "dev" for branch "dev". */
  branchPrefix?: string;
}): string {
  const { slug, ports, redisDb, auth, portless, branchPrefix } = opts;

  const host = (sub: string) => `${sub}.${branchPrefix}.dev`;
  const local = (port: number) => `http://localhost:${port}`;

  const lines: string[] = [];
  lines.push("# Generated by crbn. Do not edit by hand.");
  lines.push("# Vite/React Router auto-load this file alongside .env;");
  lines.push("# values here override .env. The user's .env is left untouched.");
  lines.push("");
  lines.push(`CARBON_WORKTREE=${slug}`);
  if (portless) lines.push("PORTLESS_TLD=dev");
  lines.push("");
  lines.push("# Internal compose ports (apps do not read these directly)");
  for (const [k, v] of Object.entries(ports)) lines.push(`${k}=${v}`);
  lines.push("");
  lines.push(
    portless
      ? "# App-facing URLs (portless hostnames)"
      : "# App-facing URLs (localhost)"
  );
  lines.push(`DOMAIN=${portless ? `${branchPrefix}.dev` : "localhost"}`);
  lines.push(
    `ERP_URL=${portless ? `https://${host("erp")}` : local(ports.PORT_ERP)}`
  );
  lines.push(
    `MES_URL=${portless ? `https://${host("mes")}` : local(ports.PORT_MES)}`
  );
  lines.push(
    `VERCEL_URL=${portless ? `https://${host("erp")}` : local(ports.PORT_ERP)}`
  );
  lines.push(
    `CARBON_API_URL=${portless ? `https://${host("erp")}` : local(ports.PORT_ERP)}`
  );
  if (portless) lines.push(`GTM_URL=https://${host("starter")}`);
  lines.push("");
  lines.push("# Database");
  const migrationDatabaseUrl = `postgresql://carbon:carbon@localhost:${ports.PORT_DB}/carbon`;
  const appDatabaseUrl = `postgresql://carbon_app:carbon_app@localhost:${ports.PORT_DB}/carbon`;
  const serviceDatabaseUrl = `postgresql://carbon_service:carbon_service@localhost:${ports.PORT_DB}/carbon`;
  lines.push(`DATABASE_MIGRATION_URL=${migrationDatabaseUrl}`);
  lines.push(`DATABASE_URL=${appDatabaseUrl}`);
  lines.push(`DATABASE_SERVICE_URL=${serviceDatabaseUrl}`);
  lines.push(`JOBS_DATABASE_URL=${serviceDatabaseUrl}`);
  lines.push("PGSSLMODE=disable");
  lines.push("");
  lines.push("# Auth");
  lines.push("AUTH_PROVIDER=better_auth");
  lines.push(`BETTER_AUTH_SECRET=${auth.secret}`);
  lines.push("");
  lines.push("# S3-compatible storage");
  const s3Endpoint = portless
    ? `https://${host("storage")}`
    : local(ports.PORT_STORAGE);
  const publicBucket = `carbon-public-${slug}`;
  const privateBucket = `carbon-private-${slug}`;
  lines.push("S3_REGION=us-east-1");
  lines.push(`S3_ENDPOINT=${s3Endpoint}`);
  lines.push("S3_ACCESS_KEY_ID=carbon");
  lines.push("S3_SECRET_ACCESS_KEY=carbon-password");
  lines.push(`S3_PRIVATE_BUCKET=${privateBucket}`);
  lines.push(`S3_PUBLIC_BUCKET=${publicBucket}`);
  lines.push(`S3_PUBLIC_BASE_URL=${s3Endpoint}/${publicBucket}`);
  lines.push("");
  lines.push("# MinIO service aliases");
  lines.push(
    `MINIO_URL=${portless ? `https://${host("storage")}` : local(ports.PORT_STORAGE)}`
  );
  lines.push(
    `MINIO_CONSOLE_URL=${portless ? `https://${host("console")}` : local(ports.PORT_CONSOLE)}`
  );
  lines.push("");
  lines.push("# Aux services");
  lines.push(`REDIS_URL=redis://localhost:${SHARED_REDIS_PORT}/${redisDb}`);
  lines.push("INNGEST_DEV=1");
  lines.push(`INNGEST_BASE_URL=http://localhost:${ports.PORT_INNGEST}`);
  // SDK advertises this as its serve URL during self-register. Must be
  // reachable from inside the inngest container (handled via extra_hosts +
  // portless CA mount in docker-compose.dev.yml).
  lines.push(
    `INNGEST_SERVE_HOST=${portless ? `https://${host("erp")}` : local(ports.PORT_ERP)}`
  );
  // Hostname (no scheme) that docker-compose maps to host-gateway inside the
  // inngest container, so the SDK URL above resolves to the dev server on the
  // host. extra_hosts only accepts fully-qualified names — no wildcards —
  // which is why we can't reuse ${DOMAIN} (e.g. `main.dev` won't match the
  // `erp.main.dev` host the SDK URL points at).
  lines.push(`INNGEST_TLS_HOST=${portless ? host("erp") : "localhost"}`);
  lines.push("");
  return lines.join("\n");
}

export function writeEnv(worktreeRoot: string, content: string) {
  writeFileSync(join(worktreeRoot, ".env.local"), content);
}

export function syncAppPortlessConfigs(worktreeRoot: string) {
  for (const { value: appId } of APP_CHOICES) {
    const path = join(worktreeRoot, "apps", appId, "portless.json");
    if (existsSync(path)) {
      unlinkSync(path);
    }
  }
}
